### ISSUE TITLE
Error relating to temporary directory.

### ISSUE THREAD

**Issue by rdamen** [greghendershott/racket-mode#100]
Hi,

I am getting the following error:
```elisp
; rename-file-or-directory: cannot rename file or directory
;   source path: /var/tmp/-home-ron-.emacs.d-elpa----224.1849-cmds.rkt-43-17_14248612571424861257323
;   dest path: /tmp/racket-mode-command-ouput-file29769G_K
;   system error: Invalid cross-device link; errno=18
```

My system has a tmpfs for /tmp and a normal /var/tmp.

In your cmds.rkt file you use the ```make-temporary-file``` function which depends on the result of```(find-system-path 'temp-dir)``` in this case /var/tmp because Racket prioritizes it over /tmp for some reason.

Emacs calls racket-mode's run.rkt with file created by Emacs ' ```(make-temp-file "racket-mode-command-output-file")```. The Emacs' ```make-temp-file``` functions uses /tmp.

I can work around this by setting the TMPDIR environment variable but it would be nice if it would work out of the box.

Thanks!

PS. I'm pretty new to both Emacs and Racket so it might be a configuration error on my part, in that case my sincere apologies.

**Comment by greghendershott** [comment]
This business of writing command output to a file, instead of mixing it in stdout, is just a few days old. You found a corner case that hadn't occurred to me. So: (a) dang (b) thanks! (c) sorry!

I think a good fix would be for the Racket code to stop using `make-temporary-file`. Instead simply use the Emacs-provided command output file name; append `".tmp"` to it. In fact the more I think about it, I should have done that in the first place. That's guaranteed to be on the same file system. (Well... vastly more likely.)

Plus, that way, if it ever turned out that even Emacs `make-temp-file` doesn't behave as desired for in some cases? That's probably a generic Emacs setting to tweak. And/or it would be straightforward enough to add some `defcustom` to override this. The lower level Racket code would follow along with that, as well.

**Comment by rdamen** [comment]
Awesome! Thank you!
