### ISSUE TITLE
racket/gui disabling racket-mode parameterizations

### ISSUE THREAD

**Issue by yn** [greghendershott/racket-mode#112]
Take this file: 

    #lang racket
    (define a 1)
    (require racket/gui)

Then C-c C-k to start the REPL. Then at the repl: 
    
    (define a 2)

See error:
   
    ; define-values: assignment disallowed;
    ;  cannot re-define a constant
    ;   constant: a
    ;   in module: "/Users/yn/code/mine/grader/bridge/mac/test.rkt"

**Comment by yn** [comment]
It's worth clarifying that without (require racket/gui) it's possible to redefine things in the REPL that are originally defined in the file.

**Comment by greghendershott** [comment]
Thank you for the report.  I can repro it.

Loading racket/gui appears to be nuking a variety of parameterizations. One of which is `compile-enforce-module-constants`. racket-mode sets this `#f` to allow redefinitions in the REPL. But the require of racket/gui is resetting this to the default `#t`.  It's stuck that way until the Racket process is reset. Even if you `racket-run` other files.

That's not the only parameterization. The recent errortrace support becomes disabled, because `current-eval` is also reset to the default.

But I don't immediately understand why this is happening. Will investigate...

**Comment by greghendershott** [comment]
OK I figured this out. I have a fix. Before I push, I'm reviewing the code more. The cause of this bug was too subtle for my taste (the timing of when a thread is created, differing for the GUI vs. not cases). I'm considering if I can restructure the code to make it more obvious. Otherwise I'll comment it heavily.
