### ISSUE TITLE
Make macro expansion menu items and key bindings available in the REPL

### ISSUE THREAD

**Issue by khinsen** [greghendershott/racket-mode#128]
The "Macro Expand" submenu of the "Racket" menu, and the associated key bindings, make as much sense in the REPL as in a Racket source code file, but they aren't there. The commands work fine when run via `M-x`, so this should be easy to add.

**Comment by greghendershott** [comment]
That's a good point!

One small catch is the key bindings. Because it is based on `comint-mode`, `racket-repl-mode` comes with a huge number of key bindings; some useful, some less so.

In `racket-mode` the macro expansion commands are all prefixed with <kbd>C-c C-e</kbd>.  Using that in `racket-repl-mode` would override `comint-mode`'s binding of <kbd>C-c C-e</kbd> to `comint-show-maximum-output`:

```
C-c C-e runs the command comint-show-maximum-output, which is an
interactive compiled Lisp function.

It is bound to C-c C-e, <menu-bar> <inout> <show-maximum-output>.

(comint-show-maximum-output)

Put the end of the buffer at the bottom of the window.
```

I think this is probably OK because (a) I never use this and (b) it's easy enough for people to change all the key bindings. I'm guessing you agree?

**Comment by khinsen** [comment]
Definitely. I can't remember having used that one ever.

**Comment by greghendershott** [comment]
Yeah it wouldn't occur to me, I just use <kbd>M-></kbd> for `end-of-buffer`.

I'll push a commit for this soon.

**Comment by khinsen** [comment]
Works great, thanks!
