### ISSUE TITLE
run.rkt process isn't killed automatically after closing emacs

### ISSUE THREAD

**Issue by zmnp** [greghendershott/racket-mode#158]
When I'm closing spacemacs with opened racket file and racket repl spacemacs asks this:
"Please answer y or n. Active processes exist; kill them and exit anyway? (y or n)"
I press "y" and spacemacs closes. But run.rkt process is still running.
I waited several minutes but it's still there in memory.
Is it a bug or maybe I improperly configured racket mode?
Maybe someone else has this issue?

**Comment by greghendershott** [comment]
Thanks for reporting this. Yes, I can reproduce it.

I'm paranoid about killing processes abruptly. So whenever Emacs gives me this message? I answer `n`, then go type `exit` in each `*shell*`, `*Racket REPL*`, etc. buffer, one by one. Which isn't convenient, but I'm paranoid.

I think that's why I've never noticed what you reported.

It seems like this ought to work, though.

I'll dig into the Emacs docs on processes, and, make sure that `run.rkt` isn't doing something to prevent itself from terminated (like eating/ignoring break or kill signals).

p.s. A simpler recipe is simply to <kbd>C-x k</kbd> `kill-buffer`, and answer `y` to the similar prompt. That leaves a process in memory, for me.

**Comment by greghendershott** [comment]
So the specific signal Emacs sends is `SIGHUP`. Racket presents this as `exn:break:hang-up`.

The wrinkle is that `exn:break:hang-up` is-a-kind-of `exn:break` -- the former is derived from the latter.

As a result, I need to change this code that catches C-c breaks:

```
  (define msg
    (call-with-exception-handler
     (match-lambda
       [(exn:break msg marks continue) (break-thread repl-thread) (continue)]
       [e e])
     (λ () (sync the-channel))))
```

That's handling _all_ of `exn:break`, `exn:break:hang-up`, and `exn:break:terminate`.  Therefore when Emacs sends the `SIGHUP`, we're ignoring it and continuing.

Instead we want the last two to be handled by `uncaught-exception-handler`, which will call `exit`.

So something like this, instead, works for me:
```
  (define msg
    (call-with-exception-handler
     (match-lambda
       [(or (? exn:break:terminate?) (? exn:break:hang-up?)) (void)]
       [(exn:break msg marks continue) (break-thread repl-thread) (continue)]
       [e e])
     (λ () (sync the-channel))))
```

I'll mull that over a bit to make sure I'm understanding this right, and if so push a commit.

p.s. This also means you can now merely `kill` the `racket run.rkt` process instead of needing `kill -9`.

**Comment by zmnp** [comment]
Great, thanks!
