### ISSUE TITLE
Completion problem.

### ISSUE THREAD

**Issue by hujianxin** [greghendershott/racket-mode#198]
Hi, when I'm editing a racket source file, for example, I wrote this:
```lisp
(define (hello)
  (display "hello"))
```
and when I wrote `hello` to call it, Emacs cannnot complete it, unless I run`M-x run-racket` to reload this file.

Is this reasonable?

**Comment by greghendershott** [comment]
Although I wouldn't say it's ideal, I'd say it's reasonable.

Occasionally it annoys me. OTOH I've thought about it a bit and believe this is the least-worst approach. I'm open to better ideas, and _really_ open to PRs. :)

For "hello" to be available for completion, at all: racket-mode needs to run (or at least expand) your program so that `namespace-mapped-symbols` will include "hello".

So for "hello" to be available for completion, sooner than your manual `racket-run`? racket-mode would need to do this sooner. Either:

1. "Continuously" (like DrRacket background syntax checking). OR
2. "On-demand", when you trigger completion.

I'm concerned that both options would be too slow.

p.s. An idea number 3, having Emacs scan the buffer text for things like `define` is, I think, hopeless. There are also bindings from the `#lang` line and those from `require`s. Even within the buffer, there can be macros that expand to `define`s, that aren't textually apparent (macros defined either in the buffer, or given from `require`s). Doing this in Emacs would be an incomplete and buggy implementation of half of Racket's macro expander and module system.

**Comment by hujianxin** [comment]
Hi, greg,
Thanks for your detailed reply. I understand what you mean. I know a similar thing in Python called `jedi`, and it's implementation is a bit complex. I'm a beginner on Racket and Emacs, but I'll think about it seriously :smile:

**Comment by greghendershott** [comment]
One thing you could do is, after typing some definition form, with point in or at the end of the form, type <kbd>C-M-x</kbd> to run `racket-send-definition`.  Effectively that "types the form at the REPL prompt for you, invisibly".

Now `hello` _will_ complete for you.

---

You might ask, why couldn't racket-mode notice when you complete a module-level form and `racket-send-definition` automatically for you?  Good question. (a) "When you complete a module-level form" is tricky, especially with racket-mode's support for submodules -- which module?  (b) This won't always work well because [the REPL top-level is hopeless](https://gist.github.com/samth/3083053), [really](http://calculist.blogspot.com/2009/01/fexprs-in-scheme.html) so racket-mode probably shouldn't do it automatically.

Probably all of this is solve-able. But I'm leery of replacing one "obvious" limitation -- it can't complete until you re-run -- with multiple corner cases where it doesn't work as expected in some subtly confusing way.

Also more basically I just don't have bandwidth right now to tackle this.

**Comment by hujianxin** [comment]
So I have got the answer that I wanted and THANKS again. you have done a lot for this project. I'll close this issue:)
