### ISSUE TITLE
bad interaction w/ paredit and racket-mode

### ISSUE THREAD

**Issue by zenspider** [greghendershott/racket-mode#222]
I haven't isolated it entirely yet... but if you open a racket file with this and activate paredit-mode, it'll complain about unbalanced parens. AFTERWARDS, paredit-mode will activate fine, so I suspect it has to do with my hook load order or something... that racket-mode is defining something lexical to teach it about `'|#|` _after_ paredit tries to run `(check-parens)` and fails.

```
(for/list ([(raw-fn suite) (in-hash test-data)]
           #:unless (equal? raw-fn '|#|))
  42)
```

This is just a stab in the dark at this point... But I thought I'd open the issue early in case you have any insight.

**Comment by greghendershott** [comment]
I'm not able to repro this.

I automatically enable `paredit-mode` in my `init.el` like so:

```
(use-package paredit
  :ensure t
  :config (progn
            (dolist (m '(clojure-mode-hook
                         cider-repl-mode-hook
                         emacs-lisp-mode-hook
                         racket-mode-hook
                         racket-repl-mode-hook))
              (add-hook m #'paredit-mode))
            (bind-keys :map paredit-mode-map
                       ("{" . paredit-open-curly)
                       ("}" . paredit-close-curly))
            (unless terminal-frame
              (bind-keys :map paredit-mode-map
                         ("M-[" . paredit-wrap-square)
                         ("M-{" . paredit-wrap-curly)))))
```

However to repro your issue I did `M-x (remove-hook 'racket-mode-hook #'paredit-mode)`, revisited the file, and manually did `M-x paredit-mode`. I got no error about unbalanced parens.

---

An interesting thing about `'|#|` is that it _could_ be related to setting comment syntax for `#|` and `|#`. Maybe something in that regard has changed in racket-mode since the version you're using?  I'm on HEAD, of course.

**Comment by greghendershott** [comment]
p.s. By `HEAD` I mean also what's currently on MELPA.

**Comment by greghendershott** [comment]
I was reviewing issues, tried this again. Now, when I open such a file, I do get:

    File mode specification error: (user-error Unmatched bracket or quote)

**Comment by greghendershott** [comment]
Although I hadn't forgotten about this, I only recently had the time and insight to figure it out. Some "fancy" Racket stuff can't be handled in a plain Emacs syntax-table; for that racket-mode supplies a `syntax-propertize-function`. If `paredit-mode` runs (due to being in `racket-mode-hook`) _before_ the propertize function has, then `check-parens` can fail.

I think the fix is adding something like this to the end of `racket--variables-for-both-modes`:

```elisp
  ;; Issue #222: Is paredit-mode a `racket-mode-hook' or
  ;; `racket-repl-mode-hook' that is able to run soon? If so, it might
  ;; run before `racket-syntax-propertize-function' has had a chance
  ;; to propertize "fancy" things like '|#| or sexpr comments, in
  ;; which case `check-parens' might fail. Avoid that by
  ;; `syntax-propertize'-ing the entire buffer now.
  (when (or (memq #'paredit-mode racket-mode-hook)
            (memq #'paredit-mode racket-repl-mode-hook))
   (syntax-propertize (point-max)))
```

This fix the issue (in my testing so far).  I'm a little worried eagerly propertizing the whole file might be slow on larger files (although it's not in the files I've tried so far) -- ergo checking to do it only if `paredit-mode` is about to run.  But I want to mull that over.

**Comment by greghendershott** [comment]
Actually it seems fine even on obnoxiously big files.

I took my favorite [3000 line scheme file](https://github.com/christoff-buerger/racr/blob/master/racr/core.scm) from #212, and copy and pasted that form a half dozen times to make 18,000 lines. It's still "instant" for to re-visit the file.

Maybe I needn't even check for `paredit-mode`...?  More mulling....
