### ISSUE TITLE
Multi-body `cond` not indented properly

### ISSUE THREAD

**Issue by stamourv** [greghendershott/racket-mode#243]
`cond` clauses with multiple subexpressions in their body do not get indented property unless the test position is a leaf expression. 

```
(cond [x y
         z]
      [(= a x) y
       z])
```

I'm expecting `y` and `z` to be aligned, which they are in the first case, but not in the second.

`case` and `match` have the same problem (and possibly others too).

**Comment by greghendershott** [comment]
Thanks for the report. I agree your expected behavior is desirable. And, it matches DrRacket's behavior.

The status quo matches what `scheme-mode` does, because both `racket-mode` and it use `calculate-lisp-indent` from `lisp-mode` -- which is a hairy imperative function. Quick glance, I think [this is the test at issue here](https://github.com/emacs-mirror/emacs/blob/master/lisp/emacs-lisp/lisp-mode.el#L816-L819).

I need to think through whether `racket-mode` ought to copypasta its own variant of this.

**Comment by stamourv** [comment]
FWIW, ISTR quack doing it right. I just looked at its indentation code, though, and it seems to just use scheme-mode's indent, which doesn't seem to match up.

**Comment by acarrico** [comment]
A matter of taste, but I don't even like the hanging z in the conditional predicate, and I'm happy with indentation following the parens in the second clause.

**Comment by greghendershott** [comment]
I don't see how Quack could do so, either.

I do like the desired/expected behavior -- both personally/specifically, and also generally because I think racket-mode and DrR should indent consistently. I'll look at this more when I can find time.

Meanwhile it will be moot to the extent you can avoid those imperative `y`s? 😛

**Comment by stamourv** [comment]
Imperative is easy enough to avoid. Internal definitions, though, those are the bee's knees. :smile:

**Comment by greghendershott** [comment]
Seemingly related: http://emacs.stackexchange.com/questions/29477/how-to-properly-indent-application-in-scheme-mode

**Comment by greghendershott** [comment]
As a heads-up, and as I just mentioned on #262:

I decided to jump down the rabbit hole and overhaul the indentation.

I already have fixes for this and #262. I want to simplify things more, if possible, so I plan to keep working on that -- but if it takes too long I'll go ahead and push commit(s) for the fixes.
