### ISSUE TITLE
enhancement: treat #'(blah) as a single s-expr

### ISSUE THREAD

**Issue by rntz** [greghendershott/racket-mode#244]
Currently commands such as `forward-sexp`, `backward-sexp` and `kill-sexp` understands that quotes `'`, quasiquotes `` ` ``, and unquotes `,` create a single s-expression; but does not understand the corresponding syntax `#'`, quasisyntax `` #` ``, and unsyntax `#,`. This means if I `kill-sexp` with point in front of `'foo bar baz`, I get ` bar baz`; but if I `kill-sexp` with point in front of `#'foo bar baz`, I get `foo bar baz`. It would be nice if, in Racket-mode, I consistently got ` bar baz`.

This would in particular help for users of paredit-mode.

**Comment by greghendershott** [comment]
Hmm, this sounds like https://github.com/greghendershott/racket-mode/issues/135, which I fixed -- AFAICT -- about a year ago.

I say "AFAICT" because (a) initially I wasn't able to reproduce #135 myself and (b) I don't now see on #135 that @parenthetical ever explicitly confirmed it got fixed, for them. So I suppose there could be another scenario or interaction with another Emacs package/mode ...?  Unless you have a quite old version of racket-mode. :)

Could you please <kbd>M-x racket-bug-report</kbd> and paste here?  (I want to confirm your Emacs and racket-mode versions, and eyeball other settings and active minor modes.

**Comment by rntz** [comment]
Oops. As it turns out, I guess I haven't upgraded my emacs packages in over a year. I kinda... forgot that it doesn't do that automatically. Herp.
