### ISSUE TITLE
`current-namespace` is wrong when running with <f5>

### ISSUE THREAD

**Issue by samth** [greghendershott/racket-mode#247]
This program:

```racket
#lang racket
(eval '(+ 1 2))
```

when run with `<f5>` in racket-mode prints 3, but when run with `C-M-<f5>` (or at the command line) produces this error:

```
[samth@hermes:~/tmp plt] +: unbound identifier;
 also, no #%app syntax transformer is bound
  at: +
  in: (+ 1 2)
  context...:
   /home/samth/tmp/yy.rkt: [running body]
```

**Comment by greghendershott** [comment]
Because I'm worried this topic is over my head, I'm going to say a few things and wait for you to correct and/or enlighten me. :)

`racket-run` is equivalent to `enter!`-ing a file (and the `,enter` command in xrepl).

It is `dynamic-require` + `module->namespace` + `read-eval-print-loop`.

In other words, if `ns.rkt` is

```
#lang racket
(eval '(+ 1 2))
```

Then:

```
$ racket
Welcome to Racket v6.7.
> (enter! "ns.rkt")
3
```

**Comment by samth** [comment]
If you put that call to `enter!` in a module, it also fails in the same way (the same as just doing the `dynamic-require`) -- at the top-level repl it's inheriting the namespace from the repl. What's going on in racket-mode, I think, is that racket-mode sets the `current-namespace` before doing the `dynamic-require`. Therefore, the call to `eval` sees that namespace and works. 

It might be that you want this behavior, but it's different than DrRacket's <f5> behavior. To get behavior like DrRacket, you'd want to run the `dynamic-require` in a namespace created with `make-base-empty-namespace`.

**Comment by greghendershott** [comment]
> To get behavior like DrRacket, you'd want to run the dynamic-require in a namespace created with `make-base-empty-namespace`.

I _think_ that's what I'm already doing:

[`(parameterize* ([current-namespace ((txt/gui make-base-namespace make-gui-namespace))])`](https://github.com/greghendershott/racket-mode/blob/master/run.rkt#L57-L61)

then

 [`(dynamic-require mod-path #f)`](https://github.com/greghendershott/racket-mode/blob/master/run.rkt#L98)

**Comment by samth** [comment]
No, there's a big difference between `make-base-empty-namespace` and `make-base-namespace` (the `-empty` part, which is crucial).

**Comment by greghendershott** [comment]
Thanks!

1. Oops. My brain read what it wanted to see there.

2. Yes, using `make-base-empty-namespace` (and `make-gui-empty-namespace`) does elicit the expected behavior when entering a module. I'll push this in a commit.

3. When entering no module (e.g. from using `,top` to get a REPL with a `>` prompt), it is still good to use the non-empty variants so I'll keep those for that case.
