### ISSUE TITLE
curry undefined in Emacs Racket REPL

### ISSUE THREAD

**Issue by castle-bravo** [greghendershott/racket-mode#260]
When I try to use `curry` in the Emacs Racket REPL, I receive the following error message (example case included):
```
Welcome to Racket v6.3.
﻿> (define succ (curry + 1))
; curry: undefined;
;  cannot reference undefined identifier
```
I do not have the same issue in the terminal-based REPL, so I think the issue is with racket-mode. Thanks!

**Comment by greghendershott** [comment]
That's because when the prompt is just `>` (i.e. no Racket file) `racket-repl-mode` defaults to `#lang racket/base` not `#lang racket`.

You could `(require racket)` or `(require racket/function)` to get `curry`.

---

The main use case for `racket-repl-mode` isn't really as a stand-alone REPL. Instead it's a "companion" to a `.rkt` file open in a `racket-mode` buffer, that you <kbd>C-c C-k</kbd>ed.

See also #110.
