### ISSUE TITLE
Cannot auto complete when the file contains error

### ISSUE THREAD

**Issue by ikzk** [greghendershott/racket-mode#272]
If I open a racket source code file containing error, then the whole completion function will not work with an error message like this:

```
Company: backend company-capf error "Process racket-command not running" with args (candidates hash-re)
```

Personally I think we should not assume every file we want to edit is runnable.

**Comment by greghendershott** [comment]
Two things here:

1. It's intentional that you can't complete until the file is `racket-run`, because:
  - To determine the completion candidates we need to use [`namespace-mapped-symbols`](https://docs.racket-lang.org/reference/Namespaces.html#%28def._%28%28quote._~23~25kernel%29._namespace-mapped-symbols%29%29).
  - To use that we need to have a namespace.
  - To get that we need to e.g. use `module->namespace` on the file.
  - That's effectively `racket-run`.

    I agree this is annoying. It annoys me!  Unfortunately I don't have a better answer. Could `racket-mode` provide some "default" completion candidates?  Sure, but what should they be? The symbols from `#lang racket`? `#lang racket/base`? `#lang typed/racket`?  What if the file `#lang unusual`?  So...I don't know. I'm open to suggestions/ideas!

2. To communicate that it's intentional, `racket-mode` gives the message, ``Completions not available until you ‘racket-run’ this buffer``. I'm not sure why you're not seeing that. Maybe because you're using an older `racket-mode`, or, maybe it's related to `company-mode`? I'll investigate that.

**Comment by greghendershott** [comment]
Also, when `company-mode` is involved, so is its "show docs" feature, for which `racket-mode` uses its `racket-describe` feature.  For that to work properly, it needs to know which identifier is meant -- from which module. For example is it the `define` from `racket` or `typed/racket`. To do this properly means having a true identifier from a Racket namespace, not just the text `"define"`. Which again means some equivalent of `racket-run`-ing the file.

**Comment by ikzk** [comment]
Thanks for your reply Greg! From your response it seems that we have this problem because the completion candidates are given by actually running the code instead of using a static analysis tool?

It seems to me this is what most REPLs do (e.g. IPython, the completion candidates change as we run more statements). This makes sense because in a REPL we run statements one by one and we make sure the previous lines are run correctly. Most IDEs (also some modes in emacs, e..g. anaconda mode for Python) use static analysis tools (e.g. jedi for Python) to perform this task. In this way errors can be tolerated.

I just did a quick search and did not see any mature static analysis lib for racket. Maybe that's the reason why we have to run the code to get completions?

How about the following suggestion: when we start `racket-mode`, the repl only reads the first line specifying the language and provides basic completion for that language. We can then send the parts of the file we want to run to the repl manually and interactively to give the repl more and more information (and only the information we want to give the repl). (I think this is some other modes in emacs do). In this way we can manually avoid sending code containing error to the repl and we have the full control of what we want to complete. Does this make sense to you?

**Comment by greghendershott** [comment]
Thank you for the suggestion!

Although there is a `#lang racket/load`, which is effectively the same as, "just type these expressions at the REPL one by one", it's rarely used. ["The top-level is hopeless"](https://gist.github.com/samth/3083053). We use modules.

A file `foo.rkt` starting with `#lang language` reads as `(module foo language expressions ...)`.

If instead of evaluating that `module` expression, we evaluate `expressions` one-by-one at a REPL -- it won't have the same result.

As just one example, within a `module` form, it is OK to have forward references (you can use a binding before it is defined; you're not obligated to `declare` as in Clojure). There are more examples; see "hopeless".

(And that's just for "vanilla" `#lang racket`.  For langs that provide an interesting `#%module-begin`, it _really_ won't work.)

So I think there's just no way to change `racket-run` this way.

---

But. I _totally_ understand the complaint re completions. I myself am annoyed when I'm editing a file that failed to run due to an error.  I'm as likely to want completion to work, then. Maybe more so!

So maybe there is some strategy to try, but only if/after there was an error. Maybe we could try to do what you describe, with the module language and `require`s, at least until _that_ maybe also fails, and use whatever we've accumulated for completions.  Would that be satisfactory, or, backfire somehow (e.g. the completions differ in unexpected ways)?  I'm not sure.

**Comment by ikzk** [comment]
Thanks! I support making what I suggested as a backup method when there is an error (and we can display a message in the minibuffer if that causes confusion). It seems to me that we will not sacrifice anything in this way.

It seems that currently using racket-run, after we add more definitions in the file, the completion candidates for these new definitions are not shown until I actually send them to the repl. Is this effectively something like what I described? If so, does this imply when we add more definitions, we should call `racket-run` again instead of just sending the added parts to the repl?

**Comment by greghendershott** [comment]
The intended workflow is similar to DrRacket:

1. You `racket-run` run the file.
2. You can explore the results in the REPL. For instance, try calling a function that you defined in the source file.
3. You _can_ also use the usual Emacs lispy commands to send just fragments of the file to the REPL to be evaluated. This is merely a shortcut for copy and paste.
4. The REPL is merely a transient playground. The next time you `racket-run`, the state of the REPL is _completely_ reset to the result of evaluating the _file_. Nothing you did _only_ in the REPL survives. And that's considered to be a good thing.

In other words, ground truth is your source file (hopefully as managed by git).

(Admittedly this is in contrast to a strand of lisp heritage where you poke mutable state in the REPL... and hope you can recreate it later. Some thoughts about that [here](http://blog.racket-lang.org/2009/03/the-drscheme-repl-isnt-the-one-in-emacs.html).  I'm not saying that style is wrong. I am saying racket-mode isn't attempting to support that.)

---

So, I think it's a given for racket-mode that completions will be available only after `racket-run`.

The interesting question is what we were discussing above: What if `racket-run` encounters some Racket syntax error? Could it try to evaluate as much _else_ of the file as possible, to at least get some useful completions?  Probably it could.

I'm worried about files having top-level expressions like `(push-the-red-button!)`.  If the user chooses `racket-run`, they know those will be executed.  So that's OK.  The part I'm worried about is, could `(push-the-red-button!)` misbehave based on some prior error-filled expressions not having been evaluated -- as part of this fallback effort to "run as much as possible for the sake of completions".

It might be safe to limit this to the module language and `require` forms. Caveats:

- That's only likely to work well for `#lang racket` flavor langs, where the symbol `require` actually expands to the actual require identifier. That's probably acceptable.
- It would mean that definitions _in_ the file aren't available for completion. But maybe `dabbrev` would suffice for that?

**Comment by greghendershott** [comment]
As an update, I've been working on this. It turned out to be trickier than I expected. Or at least, slower (for me) to figure out than I expected.

I think I'm getting close?  But I want to dog-food it for awhile.

Some WIP on [this branch](https://github.com/greghendershott/racket-mode/tree/completions-fallback).

**Comment by ikzk** [comment]
Thanks! I saw your commit and that is actually better than what I expected! I previously thought we can just read the `#lang` line and give a repl for that language :)

**Comment by greghendershott** [comment]
Yesterday I thought this was ready and squashed to a single commit on a new [`issue-272` branch](https://github.com/greghendershott/racket-mode/commits/issue-272) in preparation for merging.

But this morning I noticed it showed the error message twice, when the error is in a file `require`d by the file you're running. So another commit to fix that.

I'll live with it more, to see if I notice anything else.

Will likely re-squash before merging.
