### ISSUE TITLE
"exists -> ∃" should not be done in #:exists

### ISSUE THREAD

**Issue by enjelbeteu** [greghendershott/racket-mode#274]
When I type exists in racket mode, it automatically transforms to ∃, which can't be recognized by racket interpreter.(unlike λ)
I have added this hook:
(add-hook 'racket-mode-hook      #'racket-unicode-input-method-enable)
Sometimes I use (with-output-to-file "file" (lambda () (display "xxx")) #:exists 'truncate), so I think "exists -> ∃" should not be done in #:exists

**Comment by SFurnace** [comment]
This won't happen on my computer. I don't think racket-mode will automatically do that, maybe that is some other emacs-mode (eg. prettify-symbols-mode) does.

**Comment by greghendershott** [comment]
I'm not an expert on Emacs input methods -- and the Racket Unicode input method is one of the few racket-mode features that I don't use day-to-day myself.

From reading [Input Methods](https://www.gnu.org/software/emacs/manual/html_node/emacs/Input-Methods.html) it looks like the two choices are:

- After typing "exists" type <kbd>C-\ C-\ </kbd>.

OR

- Stop using `racket-unicode-input-method-enable` completely. Instead, use <kbd>C-x 8 RET</kbd> and type the Unicode character name.

Maybe there are other choices I don't know about?

**Comment by greghendershott** [comment]
Also, maybe racket-mode should define some default/reasonable `pretty-symbols-alist` similar to its Unicode method, for people -- maybe you?? -- who would prefer to use that instead.

`prettify-symbols-mode` is relatively new (Emacs 24.4). It works differently. If you type (say) `lambda` it does not actually replace those characters with the `λ` character -- it merely _draws_ it that way (it's implemented as a kind of font-lock a.k.a. syntax highlighting using "overlays", IIUC). The actual characters in the file are still `lambda`.

This has the advantage that you can use pretty symbols even if the programming language doesn't recognize them. It has the disadvantage that indent and alignment will sometimes look weird (because it will still work based on the actual characters, not what's displayed).

So, because this is Emacs, there are many ways to accomplish this. :)

**Comment by greghendershott** [comment]
I made a bunch of edits to my previous comment, so, if you're reading it via email, you may not have them and might want to read it on GitHub -- sorry!

**Comment by greghendershott** [comment]
I'm going to close this assuming it was a question, answered. Feel free to comment if you disagree.

Also feel free to log a fresh issue if you think racket-mode should set `prettify-symbols-alist` to some reasonable default.
