### ISSUE TITLE
Highlighting of argument names affects closing parens

### ISSUE THREAD

**Issue by david-christiansen** [greghendershott/racket-mode#276]
I just did a MELPA update, and it seems that `font-lock-variable-name-face` is being applied to too much.

In this screenshot, check out the highlighting of `stx` and `foo`:
![hl1](https://user-images.githubusercontent.com/115330/30172639-692613fe-93c3-11e7-9daa-549be0781100.png)
The following parens also have `font-lock-variable-name-face` applied.

Putting a space after `foo` makes the extra highlighting go away:
![hl2](https://user-images.githubusercontent.com/115330/30172664-7ecf2db2-93c3-11e7-8ef7-74d25b7f0b97.png)

So I suspect that this is a regexp matching too much.

**Comment by greghendershott** [comment]
Dang. I haven't noticed this dog-fooding because I use [paren-face](https://melpa.org/#/paren-face) to "dim" parentheses and that was hiding the problem. (And even when I disable `paren-face-mode`, the problem is _slightly_ subtle in solarized light or dark themes. But it's _very_ obvious in something like Material dark!)

I do have font-lock tests using the awesome [faceup](https://melpa.org/#/faceup) package. I'm surprised those didn't catch this. So I'll also investigate that.

**Comment by david-christiansen** [comment]
That looks like a nice testing system! Next time I make a fancy major mode, I'll give it a shot.

Thanks for taking a look at this.

**Comment by greghendershott** [comment]
Yes it's great -- so is [font-lock-studio](https://melpa.org/#/font-lock-studio) by the same person!

It turns out I simply didn't have any example of `(define-thing foo)` -- with no value after the `foo` -- among the tests. I just added one as a regression test.

Should be able to push a commit to fix, shortly.

**Comment by david-christiansen** [comment]
Thanks!

**Comment by greghendershott** [comment]
You're welcome, and thanks for reporting it!
