### ISSUE TITLE
slow auto-completion with company-mode

### ISSUE THREAD

**Issue by jpathy** [greghendershott/racket-mode#287]
Hello,
With company-mode enabled, sometimes it becomes extremely slow to navigate the popup window. I see run.rkt shootup in top during that time. Any idea on what might be causing this issue/or how should i debug it properly?

Edit: I am using spacemacs; but disabling company-mode on the buffer doesn't cause such "hang-up".

**Comment by jpathy** [comment]
I looked into codebase a bit and it is a problem with `type` command. It seems like `find-signature` is the real culprit of slow-down; it is doing too much work for little benefit, most definitions don't produce a signature anyway.

Maybe add a user config to disable signature doc. One can always do `racket-describe` . For now i have disabled `company-docsig`.

**Comment by greghendershott** [comment]
Thank you for researching this.

This seems like a variation on the theme, ["eldoc is too slow and anyway it's not very useful for Racket"](https://github.com/greghendershott/racket-mode/issues/199#issuecomment-179918652), that I'd overlooked because I don't actively use company-mode.

Your comment above suggests an interesting idea. `type` tries in order to find one of the following:

1. A Typed Racket type.
2. A contract.
3. A documentation contract (i.e. what people sometimes call a "blue box").
4. A signature from the definition in source code.

Of these, 1 and 2 are super-fast, 3 is quite fast, but 4 can be slow.

So, maybe there should be an option with a few levels:

- Everything on (status quo)
- Disable just 4, the `find-signature` code walk
- Disable everything (i.e. `type` always quickly returns nothing)

**Comment by jpathy** [comment]
Maybe, the find-signature work could be done one-time by the user(by an emacs command) and stored in a sqlite db(or some other option), and then 4 could be fast enough to not be a problem?

**Comment by greghendershott** [comment]
Closed with commit 2eabe36.
