### ISSUE TITLE
Allow "one-time instantiation" of other modules

### ISSUE THREAD

**Issue by iitalics** [greghendershott/racket-mode#291]
It would be nice to be able to configure what modules can be instantiated, besides just `racket/gui`.

**Comment by iitalics** [comment]
I'd like to try to implement this, I'm guessing that the work required is going to be something along the lines of:

* Change `load-gui` to specify modules to be loaded
* Create parameter for one-time-inst modules
* Implement lookup in `repl-module-name-resolver`
* Send configuration from elisp to REPL server on startup
* Document it

**Comment by greghendershott** [comment]
This exists to handle the fact that `racket/gui` has unusual limitations: See [here](https://www.mail-archive.com/racket-users@googlegroups.com/msg21853.html) and also #26.

What other modules do you have in mind? Are we sure they have a similar unusual constraint?

**Comment by iitalics** [comment]
I was hoping I could reduce reload time in the REPL for `redex` but now I'm not _entirely_ sure if this would help that.

**Comment by greghendershott** [comment]
I think the "one-time instantiation of racket/gui" business is _probably_ not quite the same thing but I'm not sure (and don't have time to dig in deep on that right now).

Also that's a part of racket-mode where I tread carefully. So I wouldn't want you to feel frustrated if you spend a lot of time but it turns out I'm very slow to review or merge a pull request touching it.

But, having done all that expectation-setting, :smile: I don't want to discourage you from experimenting, especially if you find a way to make faster what you want!

**Comment by greghendershott** [comment]
Another technique that may help is to use `raco make` or `raco setup` on some of your own Racket source files to compile them to bytecode ZO files. This especially helps when you are requiring something that does a lot of macro-expansion (for example when you're using Typed Racket) but it can help generally. I'm not sure how much it would help with your projects using Redex.

Anyway, for now I'm going to close this issue as it relates to this aspect of racket-mode preserving one instantiation of racket/gui.
