### ISSUE TITLE
Trimming requires required by submodule

### ISSUE THREAD

**Issue by pmatos** [greghendershott/racket-mode#312]
It seems that the `racket-trim-requires` is removing requires required by a submodule.
```
#lang racket

(require racket/dict)

(module+ test

  (define (t d)
    (for ([(k v) (in-dict d)])
      (printf "~a - ~a~n" k v))))
```

This works just fine until you run `racket-trim-requires` at which point, it removes `racket/dict` require and it stops working. If anything, it should move the require into the submodule.

**Comment by greghendershott** [comment]
Yes, unfortunately I think this is variation on #46, and they share the root cause racket/macro-debugger#3.

These racket-mode commands are wrappers around [`check-requires` from `macro-debugger/analysis/check-requires`](https://docs.racket-lang.org/macro-debugger/index.html#(mod-path._macro-debugger%2Fanalysis%2Fcheck-requires)), and it seems that wasn't really updated for `module+`/`module*` submodules. I looked into its code, thinking I'd volunteer a patch, but wasn't able to understand how it worked.

**Comment by greghendershott** [comment]
See also #76 and racket/macro-debugger#3.
