### ISSUE TITLE
localhost + port isn't safe

### ISSUE THREAD

**Issue by cwebber** [greghendershott/racket-mode#327]
We had to [fix a similar issue in Guile last year](https://lists.gnu.org/archive/html/guile-user/2016-10/msg00007.html).  [Localhost + port isn't actually safe](https://web.archive.org/web/20171119171836/http://bouk.co/blog/hacking-developers/) in that it's possible for the browser to act as a "confused deputy" so that lines of commands can be sent to the listening REPL, thus allowing code execution.

**Comment by cwebber** [comment]
The best solution is to use a unix domain socket (basically connecting through a file which acts as a socket) rather than localhost + port.  That should work for GNU/Linux and OSX users, but not sure what to do for Windows users.  At the least the old behavior could be left as a fallback, though it might leave Windows users vulnerable.

**Comment by greghendershott** [comment]
Thanks for opening this issue!

(Note: I edited the first link URL to point to https://lists.gnu.org/archive/html/guile-user/2016-10/msg00007.html which you'd mentioned on IRC, instead of being a dupe of the second link.)

A few quick thoughts:

- The "wire protocol" is s-expressions not line-oriented. This might alter the exposure? (But I'm not necessarily saying this reduces it. And I certainly wouldn't claim this eliminates it).

- Using domain sockets might be slightly challenging because:

    - racket-mode currently supports Racket versions as old as 6.0. (Although that could increased, some Linux distributions have quite old versions, so I like to try to support them.)

    - racket-mode is delivered as an Emacs MELPA package, not as a Racket package. It tries to avoid deps on anything except the `drracket-lib` package. (It can optionally use some packages by using `dynamic-require` with some fallback if not found.)

    - Racket doesn't "natively" support domain sockets. Looking now, I see there is a [`unix-domain-sockets` package](https://pkgs.racket-lang.org/package/unix-socket-lib). Great! Unfortunately it's [`info.rkt` seems to require Racket 6.12](https://github.com/racket/unix-socket/blob/master/unix-socket-lib/info.rkt#L5).

So. This may need to be addressed in multiple facets and stages. I'm not sure when it could be out-of-box secure-by-default for most or even many users. 😦  But we could make it better soon, and more-better later.

**Comment by greghendershott** [comment]
p.s. I neglected to include the obligatory, "At racket-mode corporation, we take security very seriously....".

**Comment by cwebber** [comment]
> The "wire protocol" is s-expressions not line-oriented. This might alter the exposure? (But I'm not necessarily saying this reduces it. And I certainly wouldn't claim this eliminates it).

Yes, I even tried attacking it by opening up a connection with telnet, but I didn't actually know what protocol it used at all :)  I tried simply typing some expressions then enter, but it did nothing.

But I don't actually know what the wire format is... maybe if you can point me to it I can more easily test.

**Comment by greghendershott** [comment]
Note that the connection model is _not_ like HTTP, where the server will accept _multiple_ TCP connections at once, and there is a single request/response per connection.

Instead, the command server accepts just _one_ TCP connection at a time. It reads and writes Emacs Lisp s-expressions. The request sexpr has a unique ID `cons`ed on the front. The unique ID is `cons`ed back to the response. So multiple commands can be "in flight" at once -- multiple requests waiting for responses -- but over just the one connection that Emacs opened.[^1]

The whole server edge is a [here](https://github.com/greghendershott/racket-mode/blob/master/cmds.rkt#L188-L208). It's a lot of comments (hopefully helpful?) then just a couple dozen lines of Racket code.

[These are the various specific commands](https://github.com/greghendershott/racket-mode/blob/master/cmds.rkt#L188-L208). Note that here the initial ID is stripped off (it's the `cdr` of what came over the wire.)

---

[^1]: The fact that the command server accepts only one connection at a time might mean the exposure is greatly reduced. There's a window when the Racket back end is starting, and the Emacs front end hasn't yet connected. An attack could connect instead?  But thereafter, probably not?

**Comment by greghendershott** [comment]
Not sure if GitHub sends a new email to you for each edit? If not: I edited the URL in the first link for the server "edge" code. Should be: https://github.com/greghendershott/racket-mode/blob/master/cmds.rkt#L119-L175

**Comment by greghendershott** [comment]
In a shell you can do `racket run.rkt 55557 '(run nil 2048 nil low nil)'` to run the back end server listening on 55557.

In another shell you can use `nc` to connect, type command requests, and see responses.

```sh
$ nc 127.0.0.1 55557
(1 path+md5)
(1 ok (top . ""))
(2 def "display")
(2 ok kernel)
(3 def "displayln")
(3 ok ("/Applications/Racket_v6.10/collects/racket/private/misc.rkt" 187 10))
(4 describe "display")
(4 ok "<div><span style=\"color: #C0C0C0\"><i>procedure</i><quote>&nbsp;</quote>Provided from: racket/base, racket | Package: base</span><div class=\"SIntrapara\"><span><table cellpadding=\"0\" cellspacing=\"0\" class=\"boxed RBoxed\"><tbody><tr><td><span><div><span class=\"RktPn\">(</span><span></span><span><i><b>display</b></i></span><span class=\"hspace\">&nbsp;</span><i>datum</i><span class=\"hspace\">&nbsp;</span>[<i>out</i>]<span class=\"RktPn\">)</span><span class=\"hspace\">&nbsp;</span>&rarr;<span class=\"hspace\">&nbsp;</span><i><span>void?</span></i></div></span></td></tr><tr><td><span class=\"hspace\">&nbsp;&nbsp;</span><i>datum</i><span class=\"hspace\">&nbsp;</span>:<span class=\"hspace\">&nbsp;</span><i><span>any/c</span></i></td></tr><tr><td><span class=\"hspace\">&nbsp;&nbsp;</span><i>out</i><span class=\"hspace\">&nbsp;</span>:<span class=\"hspace\">&nbsp;</span><i><span>output-port?</span></i><span class=\"hspace\">&nbsp;</span>=<span class=\"hspace\">&nbsp;</span><span class=\"RktPn\">(</span><i><span>current-output-port</span></i><span class=\"RktPn\">)</span></td></tr></tbody></table></span></div><div class=\"SIntrapara\">Displays <i>datum</i> to <i>out</i>, similar to <i><span>write</span></i>,\nbut usually in such a way that byte- and character-based datatypes are\nwritten as raw bytes or characters. If <i>out</i> has a handler\nassociated to it via <i><span>port-display-handler</span></i>, then the handler\nis called. Otherwise, the <span>default printer</span> is used (in <i><span>display</span></i>\nmode), as configured by various parameters.</div><p>See <span>The Printer</span> for more information about the default\nprinter. In particular, note that <i><span>display</span></i> may require memory\nproportional to the depth of the value being printed, due to the\ninitial cycle check.</p><p></p></div>")
(5 exit)
$ 
```

So that's a taste of the protocol.

---

Let's say `racket-mode` is already running a live REPL.  That uses `55555` by default. A connection is open.  Now if you try say `$ nc -G 3 127.0.0.1 55555` it will timeout after 3 seconds.

I'm not saying everything is fine. But it's possibly not as bad as it could be.

**Comment by greghendershott** [comment]
> Now if you try say `$ nc -G 3 127.0.0.1 55555` it will timeout after 3 seconds.

Actually if you use the code on `master` then `nc` will just sit there, getting no response, as opposed to clearly timing out. That's because [`tcp-listen`](https://docs.racket-lang.org/reference/tcp.html#%28def._%28%28lib._racket%2Ftcp..rkt%29._tcp-listen%29%29) is getting `4` for the `max-allow-wait` arg. The example I gave above, I had tried setting the value to `1`.  (Thinking it might be belt+suspenders, in addition to what it already does, a single `tcp-accept` at a time.)

One thing I do want to change is have the `tcp-listen` `hostname` argument be `127.0.0.1` instead of `#f`.

**Comment by cwebber** [comment]
I see, thank you for the detailed explaination!  I'll have to give it a try later, but it only accepting one connection at a time probably limits the severity of this to a much narrower race condition.  Probably something good to fix, but not crazy urgent.

**Comment by greghendershott** [comment]
As for the sort of mitigation done in [that Guile commit](http://git.savannah.gnu.org/cgit/guile.git/commit/?h=stable-2.0&id=08c021916dbd3a235a9f9cc33df4c418c0724e03), I think the racket-mode server effectively already has that. If it gets a non-sexpr, it closes the connection.

Here's a transcript where the `(1 path+md5)` request gets a `(1 ok (top . ""))` response -- but a `GET / HTTP/1.1` "command" gets disconnected.

```sh
$ nc 127.0.0.1 55557
(1 path+md5)
(1 ok (top . ""))
GET / HTTP/1.1
$
```

Having said that, it would be good to add a comment [here](https://github.com/greghendershott/racket-mode/blob/92c33487f6c707880ac3f6169e7ea65ddffd1463/cmds.rkt#L150) explicitly stating that it's desirable to drop the connection and "see issue #327". So that someday no one goes to "improve" this by making it "more robust".

**Comment by greghendershott** [comment]
Using domain sockets is safe because that not something JavaScript code in a browser can do.

What if we accept a normal TCP connection, then challenge the client to do something that JavaScript in a browser cannot do.  Is one such thing, writing to an arbitrary local file?  If so, could we use that?

For example:

- The server sends an opening "banner" sexpr `(list (make-temporary-file) (current-seconds))`. For instance that might end up being the text `'("/tmp/rkttemp1234" 1535661796)`.

- The client must
    - read that from TCP
    - write it to the specified file
    - write it back over TCP

- The server
    - reads that from TCP, checks that it matches
    - reads from the file, checks that matches

Any mismatch or discrepancy, and the server closes the connection.

**Comment by greghendershott** [comment]
Thinking more: The timing business doesn't add any actual value. I edited [the previous proposal in GitHub](https://github.com/greghendershott/racket-mode/issues/327#issuecomment-417826049).

**Comment by cwebber** [comment]
That proposal sounds like it would work to me.

**Comment by greghendershott** [comment]
As a p.s., I think I may have re-invented the X server cookie solution to this problem. :)

**Comment by greghendershott** [comment]
Just an update that some details have changed -- but I don't believe this changes the substance or risk.

- Since commit 417237c a couple months ago, TCP is used for REPL I/O (as opposed to command I/O). I think this change is a wash:

  - Either way could execute arbitrary code (e.g. one command is an `eval`).

  - The TCP connection still requires supplying the random authorization code, to demonstrate that the thing making the connection is the same thing that started the back end process.

- Since commit 304acf1 a couple weeks ago, the back end picks an available so-called ephemeral TCP port. As a result the port number is less predictable, which is some small improvement -- but certainly not "random" in any strong sense.

**Comment by greghendershott** [comment]
This is moot ever since commit 2522488 as of which we no longer use a TCP connection.
