### ISSUE TITLE
xrepl in spacemacs 

### ISSUE THREAD

**Issue by abhi18av** [greghendershott/racket-mode#329]
Hi @greghendershott 

I was wondering whether it's possible to use the `xrepl` as the default repl for emacs in `racket-mode` ? 

I'm new to `racket` and I'd love to be able to interact better with `racket` within emacs itself :)

**Comment by greghendershott** [comment]
"racket-mode" the project/repo/package, is really two major-modes:

- `racket-mode`
- `racket-repl-mode`

(Plus some minor-modes like `racket-check-syntax-mode`, `racket-debug-mode`, `racket-stepper-mode` etc.)

The thing is, beyond stuff like font-lock and indent, much of what `racket-mode` does is actually delegated to `racket-repl-mode` -- which in turn mostly delegates to a back end Racket process that runs your program as well as a TCP "command server".

As a result, `xrepl` doesn't work with `racket-repl-mode`. However, `racket-repl-mode` provides similar functionality.

---

Is it possible to use only `racket-mode` -- and instead of `racket-repl-mode` use a plain command `M-x shell` with command-line `racket`/`xrepl`?  Sure. You could try this. Many `racket-mode` commands will launch `racket-repl-mode` automatically.  You might end up wanting to unbind a lot of racket-mode commands.

If you're just starting to use Racket, it might be better simply to use `racket-mode` with `racket-repl-mode` as-intended.

**Comment by abhi18av** [comment]
I understand @greghendershott , and I a learning a lot from your blogs and code. Thanks for being such a prolific contributor to `racket` :+1:

**Comment by dbriemann** [comment]
Hi, 
I ran into a similar issue now with Doom Emacs. It is possible to do `(require xrepl)` inside the racket-repl. Would it be possible to do this automatically, e.g. via `racket-repl-mode-hook`? Or inject the require into every buffer send to the racket-repl?

**Comment by greghendershott** [comment]
You can definitely type `(require xrepl)` at the `racket-repl-mode` prompt and hit <kbd>ENTER</kbd>. (You could also automate doing that from a `racket-repl-mode-hook`.)

Maybe you could help me understand:

Have you tried? What happened?

What do you want to happen?

Is there some specific xrepl functionality you're looking to use, that is something not already supplied by `racket-repl-mode`?

**Comment by dbriemann** [comment]
Yes loading this manually in the active `racket-repl-mode` is what I currently do. What I was asking is basically how to load it automatically on start of the `racket-repl-mode`. I was only suspecting that `racket-repl-mode-hook` helps there but I am kind of an emacs beginner so I didn't figure out how to actually do this.

Also it may be possible that `racket-repl-mode` offers the same features and I don't know how to use them. What I use regularly are these commands of xrepl:
```
;   describe (desc id): describe a (bound) identifier
;   backtrace (bt): see a backtrace of the last exception
;   time: time an expression
```
But `,help` shows more interesting commands I have yet to try.

Thanks!
