### ISSUE TITLE
MELPA file missing?

### ISSUE THREAD

**Issue by rtm** [greghendershott/racket-mode#332]
A straightforward `package-install` gives me

    https://melpa.org/packages/racket-mode-20180814.221.tar: Not found

`https://melpa.org/#/` contains no racket-mode.

Has this package been removed from melpa?

**Comment by xuchunyang** [comment]
Nope, see https://melpa.org/#/racket-mode.

That's because Melpa doesn't keep old versions of packages, thus you need issue `M-x package-refresh-contents` then try again.

You don't encounter such issue while using GNU ELPA since it does keep old versions, see http://elpa.gnu.org/packages/ace-window.html for example.

**Comment by rtm** [comment]
Duh, thanks.
