### ISSUE TITLE
org-mode / ob-racket

### ISSUE THREAD

**Issue by DonHugo69** [greghendershott/racket-mode#364]
Thanks a lot for for creating and maintaining `racket-mode`!

I would like to ask about your opinion regarding an `ob-racket` package. Currently, a `ob-racket` package does not exist on MELPA and the in my eyes most complete solution on github is [found here](https://github.com/DEADB17/ob-racket).

This package works well, however it works by creating a temporary file and sending it to racket via `racket --require-script ...` and thus does not support image results.

With the help of google translator and [this](http://www.maxxcan.com/racket-en-emacs/) blog post I realized that it is possible to combine `geiser` together with `ob-scheme`. But this solution still requires manual editing of the file link in order to allow org mode to display the image.

I was looking through the source code of `ob-scheme`, `geiser` and `racket-mode` and realized that the way they work is very similar. Unfortunately, my `emacs-lisp` skills are by far not enough to come up with my own `ob-racket` package and thus I wanted to ask if something like this planned or possible to implement?

**Comment by greghendershott** [comment]
As for "planned": No, because I don't have much time, and try to focus on things I'll actually dogfood. (I've never really used org babel. Probably won't in the foreseeable future. Even if I wanted to do literate-ish programming in Racket, I'd probably try it's LP lang. Or use scribble.)

As for "possible": For sure, somehow, using the technique that geiser does (which racket-mode borrowed). Ignoring pretty-printing, to start:

- Racket code:
  - [Set the `print-handler` parameter to your own procedure](https://github.com/greghendershott/racket-mode/blob/master/racket/print.rkt#L18-L21) ...
  - which in turns calls something like [this](https://github.com/greghendershott/racket-mode/blob/master/racket/image.rkt#L24-L26). Which as you can see just saves the image to a temp file and instead prints something like `#<Image: /path/to/image>`. So that's what emacs sees appear in the buffer.
- Emacs code: Then you need to set an output filter in org-mode to do [something like this](https://github.com/greghendershott/racket-mode/blob/master/racket-repl.el#L630-L687). How to set that in org-mode, I have no idea, but people who know org-mode well could probably help you with that part?

Good luck!!
