### ISSUE TITLE
Project level persistent REPL history

### ISSUE THREAD

**Issue by 11111000000** [greghendershott/racket-mode#367]
It's nice to have project level persistent REPL history between sessions.

**Comment by greghendershott** [comment]
Although I'm not sure what a "project" would mean, it sounds like this could be related to #338 someday/maybe.

Meanwhile: Would you please get back to me [on this](https://github.com/greghendershott/racket-mode/issues/344#issuecomment-479648663)?  Want to resolve that thoroughly for one REPL before contemplating N of them. :roll_eyes:

**Comment by 11111000000** [comment]
#344 fixed for me, all ok now.
Here, under the presistent REPL history for project, I mean intuitive history of the commands entered. For now, when the user restarts the REPL - all entered magic passes disappear ...

**Comment by 11111000000** [comment]
Clojure guys try to make something similar here: https://github.com/clojure-emacs/cider/issues/2363

**Comment by greghendershott** [comment]
I see.

Some searching:

- There's a built-in `savehist`.
- Reusing built-in things when possible is good.
- You can add variables to `savehist-additional-variables`.
- Apparently it doesn't work on buffer-local variables.
- `racket-repl-mode` is based on `comint-mode`.
- So its input history is in `comint-input-ring`.
- However that's a buffer-local variable.
- It might work if `savehist-additional-variables` gets a non-buffer-local variable copy (called, say `racket-repl-comint-input-ring`) of the `comint-input-ring` buffer-local variable as described [here](https://emacs.stackexchange.com/questions/4221/remembering-history-between-sessions-in-inferior-emacs-lisp-mode). That seems like almost exactly your question and answer, except for inferior-emacs-lisp-mode.

Could you try that yourself?  If you like how it works, open a PR?

Otherwise I'll try to look at this someday when I have time.

**Comment by 11111000000** [comment]
Thank you for detailed explanation, I'll try!

**Comment by greghendershott** [comment]
I noticed this is still open. Were you able to try this?

**Comment by sturgman** [comment]
> racket-repl-mode is based on comint-mode.

I found the following solution to persistent history which is something similar to what @11111000000 describes (I think?). https://oleksandrmanzyuk.wordpress.com/2011/10/23/a-persistent-command-history-in-emacs/

I'll copy the modified code here in case that page disappears. I say modified because it was originally meant for the haskell repl but works equally well here. NOTE: I am a freshman lisper (just going through the Racket tutorials) and don't quite understand everything that is happening in this code. But it gives me persistent history!

```racket
(defun comint-write-history-on-exit (process event)
  (comint-write-input-ring)
  (let ((buf (process-buffer process)))
    (when (buffer-live-p buf)
      (with-current-buffer buf
        (insert (format "\nProcess %s %s" process event))))))

(defun turn-on-comint-history ()
  (let ((process (get-buffer-process (current-buffer))))
    (when process
      (setq comint-input-ring-file-name
            (format "~/.emacs.d/inferior-%s-history"
                    (process-name process)))
      (comint-read-input-ring)
      (set-process-sentinel process
                            #'comint-write-history-on-exit))))

(add-hook 'racket-repl-mode-hook 'turn-on-comint-history)
(add-hook 'kill-buffer-hook 'comint-write-input-ring)

(defun mapc-buffers (fn)
  (mapc (lambda (buffer)
          (with-current-buffer buffer
            (funcall fn)))
        (buffer-list)))

(defun comint-write-input-ring-all-buffers ()
  (mapc-buffers 'comint-write-input-ring))

(add-hook 'kill-emacs-hook 'comint-write-input-ring-all-buffers)
```

**Comment by greghendershott** [comment]
@sturgman Although I'd clicked the "thumbs up" button, before, I want to take time to write out "thank you!", now. You provided a really nice head start.

I pushed a commit (only to a topic branch, for now) that implements this on top of the recently added ability to have multiple REPL buffers. Basically, each uniquely named REPL buffer gets its own history file.

I've only done some quick/shallow testing, so far. So I'll probably dogfood this for awhile before merging to `master`.

**Comment by sturgman** [comment]
@greghendershott I am so glad it was useful! I spent a lot of time on it back then but it definitely paid off for me.
