### ISSUE TITLE
Indentation by regex

### ISSUE THREAD

**Issue by sorawee** [greghendershott/racket-mode#370]
I would like to be able to customize indentation by regex. For instance, it is very common to have macros named `for/...` or `define/...` or `define-...`. Most of these have the same indentation configuration, so there should be no need to manually list custom forms.

Of course, if there are two matching indentation configurations: one by regex, one by exact match, racket-mode should prioritize the exact match.

**Comment by greghendershott** [comment]
<kbd>C-h f</kbd> `racket-indent-line` -- see also `Reference.md` -- explains this already happens for `def*`, `with-*`, and `begin*` forms:

> - Automatically indents forms that start with `begin` in the usual
>  way that `begin` is indented.
>
> - Automatically indents forms that start with `def` or `with-` in the
>  usual way that `define` is indented.

[Code](https://github.com/greghendershott/racket-mode/blob/master/racket-indent.el#L191-L194).

In other words, racket-mode follows the example of DrRacket in this regard, but otherwise follows the example of {lisp scheme}-mode.

DrRacket lets you change the regexp for three specific/hardwired indentation results.

Possible enhancements for racket-mode:

1. Like DrR it could let you change the regexp for the (still hardwired) indentation results.

2. Unlike DrR (and as I think you're suggesting in your new-feature idea) it could let you supply a whole list of `((regexp . indent) ...)`.
