### ISSUE TITLE
A module form might not always be a module

### ISSUE THREAD

**Issue by sorawee** [greghendershott/racket-mode#380]
For instance, `module` could be matched in `syntax-parse` like this:

```
(syntax-parse stx
    #:literal-sets (kernel-literals)
    [(module a b (#%module-begin . body))
     (println #'body)])
```

if I try to `ctrl-c ctrl-c` where the point is inside `(module a ...)` , it will attempt to run the submodule `a` which doesn't exist.

**Comment by greghendershott** [comment]
Henry Youngman has a "Doctor it hurts when..." joke that may be of interest here?

**Comment by greghendershott** [comment]
This feature is implemented up in Emacs Lisp. It looks for `module`, `module*`, and `module+` forms textually. It does try to exclude those in comments or when quoted, because that is also textually apparent.

I don't think it is worth the time/effort/complication for it to attempt more filtering by fully expanding. I think when your program defines module not to mean module, it is acceptable for this not work.
