### ISSUE TITLE
Using Minibuffer for posting results

### ISSUE THREAD

**Issue by teymuri** [greghendershott/racket-mode#386]
Is it possible to send the results of sexpression to the minibuffer (as in all emacs lisp modes) so that the repl buffer doesn't popup on every evaluation?

**Comment by greghendershott** [comment]
You could try `M-x racket-eval-last-sexp`.

Although it has a doc string, it's not documented in the reference Info or at <https://www.racket-mode.com/>.

**Comment by greghendershott** [comment]
Keep in mind that Racket functions may return zero or more values.

As a result, `racket-eval-last-sexp` always prints a list of values.

An expression that is a single value prints as a list of one: `(+ 1 1)` will print `(2)` in the echo area.

That may seem weird, and it is, but it's because it needs to handle expressions like `(values 1 2)`, which will print `(1 2)`.

**Comment by greghendershott** [comment]
Was this answer helpful?

If so, although you don't need to thank me for taking the time to answer, you could click the Close button.

**Comment by teymuri** [comment]
Sorry, i didn't have the time to check github last days. Thank you for your time and your answer!
