### ISSUE TITLE
Add to NonGNU ELPA

### ISSUE THREAD

**Issue by phikal** [greghendershott/racket-mode#389]
Hi,

I'm a MELPA Stable user, which means that I can only install software from MELPA that has had a tag added to the repository to indicate a "stable" state. Sadly `racket-mode` doesn't seem to have any published tags, so I wanted to ask if it a (somewhat?) stable point in history could be tagged?

**Comment by greghendershott** [comment]
Although I'm not necessarily opposed to doing this, ever, I'm reluctant. I'm concerned that it might be "dishonest" --- create an expectation that I'm unable or unwilling to fulfill.

The status quo:

- I set this repo so that even I can't push commits directly to `master`. And I can't merge until Travis CI says the tests pass for a wide variety of versions of Rackets and Emacs. I always create a topic branch. Even to fix a doc typo. Even if the tests pass, if some feature or fix feels risky, I wait before merging.

- On the other hand, the tests are very far from 100% coverage. Also I don't administer any "beta testing" program (I'm not sure there are even enough Racket Mode users, total, for the notion of a beta tester subset to be practical). 

That is the level of care and responsibility that I have time to aim for, currently.

---

As a result, I _could_ add a "stable" release tag to some commit, from time to time. Call it "version 1.42". But honestly it would still _mean_ "unstable" MELPA's "version _date-and-time_", or "version _commit digest_" -- the status quo, masquerading as something else.

I would not want to do this, for you, and discover I have created some expectation that I'm unwilling or unable to satisfy, for other people.

---

Having said all that, I'll mull this over.

Meanwhile you _could_ [install only Racket Mode from "unstable" MELPA](https://emacs.stackexchange.com/questions/2969/is-it-possible-to-use-both-melpa-and-melpa-stable-at-the-same-time). Of course I understand you might not want to do that, I just want to make sure you knew about that option.

**Comment by dedbox** [comment]
According to my totally scientific and unbiased Google search, users seem to view a MELPA stable tag like a GitHub release tag, which is as you just described. I use GitHub release tags to keep track of project state at major events like release announcements and conference talks.

In any case, if you start a backlog specifically for improving the existing code base -- tests, docs, whatever -- I would totally grind on those tickets in my spare time.

**Comment by phikal** [comment]
As long as there are plans to add a tag sometime in the future, I am satisfied. I've just run into too many projects that just forgot about it.

> Meanwhile you could install only Racket Mode from "unstable" MELPA. Of course I understand you might not want to do that, I just want to make sure you knew about that option.

Yeah, I know about that possibility -- I've tried it but it never worked out the way I wanted it to. If I really needed it, I could also just clone the repo.

**Comment by greghendershott** [comment]
@dedbox If that's the expectation, I'd feel better.

@phikal I think where this trips me up is, I already use my best effort to make sure `master` is stable, all the time. I don't have any extra special process that I would do, to "cut a release". (If I did, I'd want to automate it and have it happen automatically for every single commit to every topic branch, too.)

And for example, when I was working on the step-debugger feature, it was on a topic branch for some weeks or months. Not iterating on `master`.

So if you ask me today, is HEAD stable, right now? I'd say, yes, to the best of my knowledge. And I use Racket Mode myself nearly every day, so many of its features get pretty heavily dog-fooded.

But I don't know what I don't know. And with Emacs, people can be using many different mixes of modes that I do _not_ personally dog-food. So, I'm aware it is a pretty big set of don't-knows.

**Comment by dedbox** [comment]
On Wed, Jul 10, 2019, 10:07 AM Greg Hendershott <notifications@github.com>
wrote:

> But I don't know what I don't know. And with Emacs, people can be using
> many different mixes of modes that I do *not* personally dog-food. So,
> I'm aware it is a pretty big set of don't-knows.
>

By this standard, would MELPA stable be empty?

**Comment by dedbox** [comment]
Sorry if that sounded cheeky. I'm genuinely curious, but that's not so
relevant.

More directly, it sounds like you're setting an impossibly high standard
for an ecosystem as messy as Emacs'. Is there a better way to increase the
user base to surface cross-compatibility issues?

Eric

**Comment by dedbox** [comment]
And on second thought, another way of looking at it is that you've done
your due diligence in MELPA unstable (and then some), and maybe it's time
to take the leap because the release process and code base are stable
enough.

Of course, that's a big subjective 'maybe', because even a quality product
release would entail some amount of prep and follow-up that perhaps only
you could do at this point.

**Comment by greghendershott** [comment]
Just to touch base, I haven't forgotten about this, I've just been busy and keep deferring it. Realistically it will be at least another week or two until I can look at it again.

**Comment by phikal** [comment]
I'd like to bring up the issue again, but this time not from the perspective of MELPA Stable but [NonGNU ELPA](https://elpa.nongnu.org/), the new archive for packages without copyright assignments to the FSF. It will be enabled OOTB from Emacs 28 onwards, meaning that any package in NonGNU ELPA can be installed without any further configuration.

Compared to MELPA, NonGNU distributes "stable" or "tagged" releases by default. The ELPA build system doesn't determine these by checking for the most recent Git tag, but by finds the last commit that bumps the version attribute in the [package header](https://www.gnu.org/software/emacs/manual/html_node/elisp/Simple-Packages.html).

If there is any interest in adding racket-mode to NonGNU ELPA, all that has to be done is to add such a version tag (which also has the advantage that users can manually download and install the package via `package-install-file`) and maintain it in the future.

**Comment by greghendershott** [comment]
> Ok, I will see what can be done.

Thank you!

>>  (Either way, I appreciate the user-expectations discussion elsewhere in that thread, that's helpful!)
>
> I might have missed that, what are you referring to?

Probably "discussion" over-states it; I just meant: https://mail.gnu.org/archive/html/bug-gnu-emacs/2021-10/msg01818.html

Remember, my whole introduction to NonGNU ELPA is via this issue, titled "Adding a **Stable** Tag". Plus the NonGNU ELPA web site packages mostly do have "stable"-like version numbers. Plus the web site doesn't talk about "stable" vs. "rolling" --- is it silent because "stable" is assumed as the obvious right thing, or, because it's not trying to take a position either way? It helped to see Stefan Kangas say it's the latter. Even if that's just the opinion of one maintainer and not "official GNU policy", it's more than nothing; it's some indication.

Combine that with:

- A few packages there already seemingly use a rolling date for "Version".

- A proposed devel flag to automate that.

And it sounds encouraging, especially with the final item.

**Comment by greghendershott** [comment]
Thanks for following up.

A few questions:

1. So IIRC you would add Racket Mode using the new `:rolling-release` attribute. Going forward, if I push a new commit to the repo here on GitHub, it would automatically update on NonGNU ELPA, much like with MELPA?

2. On MELPA, the "version numbers" are timestamps. Out of curiosity, would it look like non NonGNU ELPA?

3. It look like a few packages currently use `:version-map` for what seems to be a rolling release, for example:

    ```elisp
    ("smartparens"		:url "https://github.com/Fuco1/smartparens"
      :ignored-files ("LICENSE" "dev" "doc" "images" "test")
      ;; See https://github.com/Fuco1/smartparens/issues/1095
      ;;
      ;; Until a version tag is added, the commit of the latest tag is
      ;; used to mark the last stable release:
      ;; https://github.com/Fuco1/smartparens/releases/tag/1.11.0
      :version-map ((nil "1.11.0" "4873352b5d0a1c5142658122de1b6950b8fe7e4d")))
    ```

    Out of curiosity, do you expect to change these to use `:rolling-release`, instead?

**Comment by greghendershott** [comment]
Two **tiny** questions/concerns:

1. The rules in README.org include:

    > *** The package must follow the rules in
    >    https://www.gnu.org/prep/standards/, node References.  This means it
    >    may not refer users to any nonfree software or nonfree
    >    documentation, except as stated there.  Leading users to run a
    >    program, and suggesting they run it, or depending on it to be
    >    installed, are forms of referring users to it.

    Although I'm not aware of doing this, currently, I also don't worry about it. If some Emacs or Racket package seems relevant, then I just point it out to people -- on the theory it's information: Each person can decide if it is actually useful, and, usable (licensing), for them.

    In practice is that going to be OK, or, be a Huge Issue if something has e.g. MIT or no explicit license at all?

2. The MELPA package definitions are in terms of files to include, whereas the NonGNU ELPA ones seem to be in terms of files to ignore. So e.g. once upon a time I added a new top-level `tests` directory -- but didn't need to ask for the MELPA definition to be updated. If I do that going forward, I'd need to contact you wrt `:ignored-files`, correct?

    (I'm not objecting, or asking you to change the definition model just for me. Really I'm just double-checking what I might need to remember to do differently.)

**Comment by greghendershott** [comment]
> NonGNU ELPA does not insist on GPL code, as NonGNU ELPA packages are
explicitly not part of Emacs (as opposed to GNU ELPA).  So MIT shouldn't
be a problem.  No license is tricky, because that is -- legally speaking
-- non-free code that you are not allowed to modify, distribute, etc.
Is this something you anticipate?

No, I don't anticipate it. I was trying to say that I don't think about it, at all. If some package seems potentially useful, my inclination is to mention it -- and let each user do their own due diligence. The rule seems to say I should not even talk about the existence of non-free items (or whatever "refer" means here).

Probably I am over-thinking this rule. If, someday, I list some "suggested package" that turns out to have a license defect, we can figure it out, then.

> You can also maintain these in your repository, by adding an .elpaignore
file that will list files to be excluded during packaging (in the
backend this makes use of GNU tar's "-X" flag).

Oh, great. I had skimmed both README and README.org, but overlooked that.

---

Thank you very much for your help explaining things. I think it all looks good now. What would be the next steps?

Should I for example:

- [ ] Add such an `.elpaignore`
- [ ] Add back a `Version:` field to `racket-mode.el` (which I'd intentionally removed when I realized was really doing a rolling release)
- [ ] Give you my attempt at the package definition for https://git.savannah.gnu.org/cgit/emacs/nongnu.git/tree/elpa-packages

**Comment by greghendershott** [comment]
I added a commit 22f45f6 with a first draft of updating `racket-mode.el` as well as adding a `.elpaignore`.

**Comment by greghendershott** [comment]
> Your .texi trick seems to have worked.

Well, not quite. Experimenting with `tar -X .elpaignore` I noticed it let slip a couple files with 3-letter extensions, .org and .css.

I was trying to be too clever, forcing it into an inclusion rule. I just changed that.

Also I fixed some other things in `.elpaignore` (e.g. it was including the whole `test` subdirectory), which I just force-pushed to that topic branch in commit 7499927.

---

As for those five image files: I'm not sure why it's referring to "(for HTML)" as opposed to the Info generation. I do generate HTML for the https://racket-mode.com web site. I'm not sure why your build script would attempt that by default? Are those warnings harmless in your opinion, or do we need to work on that?

**Comment by greghendershott** [comment]
> Generally, do you force-push a lot?  ELPA that prefers to fast-forward
the mirror if possible, so force-pushing can cause conflicts.

Absolutely never to the main branch (`master`), to which ELPA would be pointed. In fact I have GitHub branches configured to guard against this.

Sometimes I do force-push to a "topic" branch -- as in this case, the `nongnu-elpa` branch -- particularly if I know I'm going to squash down to one commit before merging, anyway. And if the spirit is to fix some typo or dumb mistake in the previous commit, and I don't think anyone is really following along with the changes one by one. Sorry if that caused any confusion, for you, here!

**Comment by greghendershott** [comment]
As for the doc warnings, thanks for confirming that.

I _think_ I've done all I need to, on my end? Of course please let me know if there's more that I should do, or anything I can do to help you.

**Comment by greghendershott** [comment]
Oh, if you're pointing ELPA to the `master` branch at GitHub, I should probably go ahead and merge my changes from the topic branch to that main branch.

Even if there were problems or additional changes to make wrt to NonGNU ELPA, that should be N/A with respect to everything else (nothing else looks at `.elpaignore`, or really cares about the `Version` or `Maintainer` metadata in `racket-mode.el`, AFAICT).

**Comment by greghendershott** [comment]
As a heads up, I just merged a commit changing a few `.md` files to `.org`, including the package's README.

So I think the definition would now be something like:

```elisp
 ("racket-mode"             :url "https://github.com/greghendershott/racket-mode"
  :rolling-release t
  :readme "README.org")
```

or even (IIUC) simply:

```elisp
 ("racket-mode"             :url "https://github.com/greghendershott/racket-mode"
  :rolling-release t)
```

**Comment by greghendershott** [comment]
Oh, no. I hope you're feeling better, soon!

Thank you again for the original issue submission, as well as following up over time, and especially for your help during this "home stretch".

**Comment by greghendershott** [comment]
I see it appeared on https://elpa.nongnu.org/nongnu/racket-mode.html. :tada:

It's been intentional that I haven't supplied an email address. I don't want spam, and also, GitHub Issues is my only "inbox" to handle bug reports and feature requests in a public and transparent way. The docs explain and link to that.

I had checked and saw the email is blank for some other NonGNU ELPA packages, so I figured it was acceptable.

Although I'm open to discussing changing this, if it's really a big deal, it is probably (for me) really a whole discussion about how to manage issues (if not solely via GitHub), and so probably deserves it's own new/fresh issue (here, ironically or not, for now).

**Comment by greghendershott** [comment]
> To clarify your point, your main concerns are Spam and centrality of
development, right?

Yes.

Sometimes on the Racket Discourse, Slack, IRC, or whatever, someone will mention an issue. Sometimes I will copy that into a newly created GitHub Issues item, here, and ask them to continue the conversation, here. It's not ideal, but it's rare. I'd rather not add an "official", email flavor of that flow.

---

I do understand that GitHub is not ideal for everyone, on practical and/or philosophical grounds; that makes me feel bad.

On the other hand, some of these issues or feature requests take a very long time for me to handle -- in some cases many days or weeks to fix or add something non-trivial for one person. I feel less bad thinking that, as part of the bargain, I ask for the workflow to be a certain, simpler way.
