### ISSUE TITLE
company-quickhelp prettify formatting

### ISSUE THREAD

**Issue by andreyorst** [greghendershott/racket-mode#405]
As in https://github.com/greghendershott/racket-mode/issues/404#issuecomment-545519400:

> The main problem turned out to be very simple to fix. Racket Mode was calling `display-buffer` when it didn't need to. Vanilla company will call `display-buffer`, so it was an unnoticed and harmless redundancy. With `company-quickhelp`, it matters.
> 
> The formatting... I started to look into it, but it wasn't immediately clear. I decided to merge the fix for this main issue. If you or someone else wants to open a new issue about the formatting -- essentially there seems to be a "missing newline" -- I'm not discouraging you. If it bothers you, please do! But I won't proactively work on it until/unless it matters enough to someone.

This issue exists, but it's not bothering me personally. I'm fine with how `company-quickhelp` displays the popup. But as a **very low priority** feature request I'm opening this very issue, so it could be here if anyone (including myself) would want to help.

# 

Currently, formatting in `*Racket Describe*` mode and `company-quickhelp` popup differs, in terms of text attributes such as **bold**, and some formatting issues (I sense some `\t` characters in alignment):

- `*Racket Describe*`: ![image](https://user-images.githubusercontent.com/19470159/67424874-a9fdb780-f5df-11e9-803f-95acdb1a3a7b.png)
- `company-quickhelp`: ![image](https://user-images.githubusercontent.com/19470159/67424902-ba159700-f5df-11e9-823b-34000ad4aa02.png)

Maybe there are more issues that can be observed with more advanced documentation pages.

# 

@greghendershott thanks for your awesome work on this mode, it's truly amazing!

**Comment by andreyorst** [comment]
Further info:

Enabling `whitespace-mode` in `*Racket Describe*` screams red:

![image](https://user-images.githubusercontent.com/19470159/67426519-ebdc2d00-f5e2-11e9-9827-dc3de2c6302a.png)

And some weird characters are used for indentation and alignment that `whitespace-mode` is not avare of. Dots, are spaces, tab should be `>>` but there are empty rectangles, that are really wide in `*Racket Describe*` buffer, and short in `company-quickhelp`

**Comment by greghendershott** [comment]
Thank you for the great screen shots and information.

**Comment by greghendershott** [comment]
I was curious and spent an hour poking around. It looks like this is because [company-quickhelp uses `buffer-substring-no-properties`](https://github.com/expez/company-quickhelp/blob/master/company-quickhelp.el#L122) instead of `buffer-substring`. In other words it deliberately discards the properties.

If I change that to use `buffer-substring` -- *and* also set `(setq company-quickhelp-use-propertized-text t)` -- then I do see the formatted text.

So, maybe this would be an issue you could raise there?

---

There might be good reasons company-quickhelp wants to use plain not propertized text, and is unwilling or unable to change this. In that case, I think the only hope is to try, here, to make the non-propertized text at least align better. That might be non-trivial because it is coming from Racket doc HTML via Emacs' [`libxml-parse-html-region` and `shr-insert-document`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Parsing-HTML_002fXML.html). I'm not sure that would be great return on investment, for me to spend time on that, but that's my quick gut reaction.

**Comment by andreyorst** [comment]
Properties are really low priority, I'll ask in `company-quickhelp` but it seems that its development is really slow and last commit is in 2018.

On alignment topic:
Maybe convert every whitespace except newline to needed amount of spaces, so alignment could be the same for every buffer that doesn't use pitch shifted fonts at very least?

**Comment by greghendershott** [comment]
Oh it looks like `company-quickhelp` was just updated and they closed that issue:

  https://github.com/company-mode/company-quickhelp/issues/98#event-3474967691
