### ISSUE TITLE
racket-eval-last-sexp doesn't format result nicely

### ISSUE THREAD

**Issue by xuchunyang** [greghendershott/racket-mode#417]
Evaluating  `123` with `M-x racket-eval-last-sexp` shows the following two lines in the echo area

```
(123)

```
as `(message "(123)\n")` does.

But I expect `(message "123")` the same as the output in Racket REPL, so the trailing newline should be remove (this should be very easy) and the () should be removed (maybe not very easy?).

`M-x racket-eval-last-sexp` should try to give the same output as Racket REPL:

```
playground.rkt> 123
123
playground.rkt> (values 1 2 3)
1
2
3
playground.rkt> (list 1 2 3)
'(1 2 3)
playground.rkt> "hello world"
"hello world"
playground.rkt> 
```

**Comment by greghendershott** [comment]
Good point.

Trying to remember my thinking here. It was probably something like: "Well, the back-end command should return the values as a list, so that they could be usable from Elisp code generally -- not only from this front-end command that just `message`s them. i.e. Maybe it could be a building block for something else."

- If that's still a valid idea, I should change the front-end command to format them in the expected way.

- Otherwise, it would be simpler to change the back-end command to e.g.:

```diff
 (define/contract (eval-command str)
   (-> string? string?)
-  (define results
-    (call-with-values (λ ()
-                        ((current-eval) (string->namespace-syntax str)))
-                      list))
-  (~a (map ~v results) "\n"))
+  (call-with-values
+   (λ ()
+     ((current-eval) (string->namespace-syntax str)))
+   (λ vs
+     (apply ~a #:separator "\n" (map ~v vs)))))
 ```
---

Since the formatting probably isn't an urgent bug, I'll take a little time to mull it over.
