### ISSUE TITLE
racket-describe: no doc for frame%

### ISSUE THREAD

**Issue by xuchunyang** [greghendershott/racket-mode#423]
```racket
#lang racket/gui

(define window
  (new frame%
       [label "test"]))

(send window create-status-line)
(send window center)
(send window show #t)
```

`racket-describe` don't show doc for [`frame%`](https://docs.racket-lang.org/gui/frame_.html?q=frame%25):

> frame%
> 
> (Found no documentation, signature, type, or contract.)
> 
> Definition   Documentation in Browser          [q]uit

**Comment by greghendershott** [comment]
I think this is something that will work better on the new `check-syntax` branch's `racket-xp-describe` command. The static analysis from `drracket/check-syntax` provides an annotation for the `"frame%"` text that has a link to the documentation, and `racket-xp-describe` can simply use that instead of trying to synthesize an identifier binding from which to find help.

So I'm going to leave this open, but like a couple other recent issues, I think merging that branch to `master` will effectively close this.

**Comment by greghendershott** [comment]
This now works when the new [`racket-xp-mode`](https://www.racket-mode.com/#racket_002dxp_002dmode) is enabled, which is now merged to `master`, so I'm closing this.
