### ISSUE TITLE
Update requires programmatically?

### ISSUE THREAD

**Issue by xuchunyang** [greghendershott/racket-mode#424]
In this following, I want to add `ffi/unsafe` to requires

![image](https://user-images.githubusercontent.com/4550353/74604986-71d63380-50fe-11ea-9c77-956054bfb661.png)

I treat the racket code as text, and use Emacs to modify it

```elisp
(save-excursion
  (goto-char (point-min))
  (when (re-search-forward (rx bol "(" symbol-start "require"))
    (backward-up-list)
    (forward-sexp)
    (backward-char)
    (call-interactively #'newline)
    (insert "ffi/unsafe")))
```
this approach works, but since Emacs doesn't understand racket code, it can't tell the difference of these two requires

```racket
#lang racket

"
(require sdl2)
"
(require sdl2)
```

though I don't worry about this in practice. But it would be nice if we can use the syntax tree to update requires.

Furthermore, I learnt that [goimports](https://pkg.go.dev/golang.org/x/tools/cmd/goimports?tab=doc) can fix requires automatically 

> Command goimports updates your Go import lines, adding missing ones and removing unreferenced ones.

it is very useful (unused requires are treated as syntax errors in Go), and in the following code, it's not difficult to figure out that `malloc` is only provide by `ffi/unsafe`, and `racket/list` is not used (don't consider the possibility of side effect),

```racket
#lang racket

(require racket/list)

malloc
```

so maybe we can add a command such as `M-x racket-requires` to change the above into

```racket
#lang racket

(require ffi/unsafe)

malloc
```

**Comment by xuchunyang** [comment]
I didn't know `racket-trim-requires` exists. It would be nice if there is also a command for adding missing requires.

**Comment by greghendershott** [comment]
I agree that would be convenient --- if it could work well.

In Racket it is not unusual for two or more libraries to export something named "foo". (Which is fine, especially with `require` subforms like `prefix-in`, `rename-in`, `only-in`, and `except-in`.)

As a result it is more the case that the `require` drives the meaning of the identifiers, than the other way around (that the identifiers could reliably tell you what to require).

In fact that's why features like help need a specific namespace or set of requires, to disambiguate and know what help to show you.

For example, [here are all the things that provide a "define"](https://docs.racket-lang.org/search/index.html?q=define).

OK, that's a weak example, because "define" would usually be defined in the module language.

A slightly better example would be ["check"](https://docs.racket-lang.org/search/index.html?q=check): Do you want the one from `rackunit` or `quickcheck`? :man_shrugging: 

---

Having said all that:

- Maybe there are some common sense heuristics to pick just one automatically?

- Maybe must make you, the user, pick from such a list?  (Even if the previous point isn't good enough to work automatically, maybe it would be OK as a way to suggest a default?)

So some nice ideas, but I'm currently still up to my eyeballs on the `check-syntax` branch.

**Comment by aymanosman** [comment]
Would it be possible to show you a list of candidates as in Intellij?

<img width="509" alt="Screen Shot 2020-02-18 at 22 57 04" src="https://user-images.githubusercontent.com/3605049/74785461-4d1ac100-52a2-11ea-9c13-8451662d3e95.png">

**Comment by greghendershott** [comment]
@aymanosman Yes for some definition of "possible". :smile:

- If this were supposed to work only for functions that have documentation? Then it would probably be easy and fast in roughly the same way as [ambiguous help works](https://docs.racket-lang.org/search/index.html?q=define).

- If this is supposed to work for functions from all collections that happen to be installed? Then I think this needs some sort of database that AFAIK doesn't currently exist.

- If this is supposed to work for functions that aren't even provided by installed collections -- e.g. some project you're working on, for which you haven't even done a `raco link` or `raco pkg install --link`? Again either a database or at least some sort of search with a cache.

---

Someday some sort of database or catalog could support certain features. For example, in the `check-syntax` branch I'm currently working on, it's really handy that when point is on a definition, it shows you how many uses exist and lets you quickly navigate among them, or rename the  def and all its uses. But that only works within the one source file. It would be neat for it to work across multiple files. I think this touches on the same sort of information.

This feels like something that e.g. `raco {make setup}` could/should build alongside building bytecode. But idk. Needs more thought and discussion. I think it's bigger than Racket Mode per se.

**Comment by greghendershott** [comment]
I have a commit to add a command to do this in terms of _documented_ exports. My intent is to merge this, but I want to dogfood it for awhile.
