### ISSUE TITLE
Does racket-debug-mode support breakpoint?

### ISSUE THREAD

**Issue by xuchunyang** [greghendershott/racket-mode#425]
In DrRacket, user can set breakpoint in some place, according to 
https://docs.racket-lang.org/drracket/debugger.html#%28part._.Definitions_.Window_.Actions%29

> Hovering the mouse cursor over a parenthesis may reveal a pink circle. If so, right-clicking or control-clicking (Mac OS) will open a menu with options to **Pause at this point** or Continue to this point. The former sets an ordinary **breakpoint** at that location; ...

Does `racket-debug-mode` support breakpoint? By the way, `racket-debug-run-to-here` doesn't seem working from here and `racket-debug-step` works.

**Comment by greghendershott** [comment]
`racket-debug-run-to-here` is the breakpoint feature.

Thanks for pointing out that it's not working. It looks like that broke at some point due to it storing the source path from Emacs as a `path-string?` --- but the source as provided by the debug annotator is always a `path?`. I pushed a commit to resolve this; will merge to `master` after CI runs.
