### ISSUE TITLE
Nested comment using `#;` messes up highlighting and navigation

### ISSUE THREAD

**Issue by philnguyen** [greghendershott/racket-mode#45]
The following program illustrates the problem:

```{racket}
    (let (#;[x #;1]
          [y 2])
      (+ 1 2))
```

This is a valid program but the highlighting and navigation by parentheses is currently messed up.

**Comment by greghendershott** [comment]
Good news, I'm close to merging some commits that fix this issue, finally.

I had to dig in and truly understand some of the stuff that I had cargo-culted from scheme-mode, as well as learn more about how Emacs does syntax tables and font-lock. Also I figured how to do effective regression tests for indentation and font-lock. Although it's turned out to be a lot of work relative to this one corner-case bug, I'm really happy I got to a point where I could dig in.
