### ISSUE TITLE
Rebinding keys for the REPL doesn't seem to work

### ISSUE THREAD

**Issue by cflewis** [greghendershott/racket-mode#456]
Hi there,
Apologies if this is a silly question. I am new to Emacs.

I am using Spacemacs and I am trying to rebind moving between windows. I like to use Ctrl+(vim movements). I have these working just fine in "normal" editors, but once I am in the Racket REPL I can't escape. C-j and C-k are performing history cycling, not movement. My read of the docs is I need to use `add-hook` and add `repl-mode-map`s, but it's not working for me.

I think I am probably doing something obviously wrong.

Here's my config:

```elisp
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration.
This is the place where most of your configurations should be done. Unless it is
explicitly specified that a variable should be set before a package is loaded,
you should place your code here."
  (define-key evil-normal-state-map (kbd "C-h") 'windmove-left)
  (define-key evil-normal-state-map (kbd "C-l") 'windmove-right)
  (define-key evil-normal-state-map (kbd "C-j") 'windmove-down)
  (define-key evil-normal-state-map (kbd "C-k") 'windmove-up)

  (spacemacs/set-leader-keys-for-major-mode 'racket-mode "r" 'racket-run-and-switch-to-repl)

  (add-hook 'racket-repl-mode-hook
      (lambda ()
        (define-key racket-repl-mode-map (kbd "C-k") 'windmove-up))
        (define-key racket-repl-mode-map (kbd "C-j") 'windmove-down))
  )
```

**Comment by greghendershott** [comment]
Hi! It's not a silly question.

By default, `racket-repl-mode-map`:

- binds <kbd>C-j</kbd> to `newline-and-indent` (so you can add another line without evaluating it yet like you would with <kbd>RET</kbd>).

- doesn't bind <kbd>C-k</kbd> specially; the default in plain Emacs is `kill-line`.

Something is overriding those `racket-repl-mode-map` bindings, e.g. some other map is taking precedence. That's probably why you setting them in `racket-repl-mode-map` doesn't help.

What's "something"?  Run the command `describe-key` (e.g. `M-x describe-key`, or whatever Spacemas does for `M-x`). It should describe the command, and in what keybinding map the binding exists.

I'm not sure to what extent Spacemacs "hides" this from you, but Emacs has major and minor modes. The major mode in this case is `racket-repl-mode`, and it has a key map, `racket-repl-mode-map`. Then there can be N other minor modes. Minor mode key maps take precedence over major mode key maps (so they can enhance/extend/tweak the major mode).

Probably some Emacs minor mode is doing this. Maybe you'll want to disable that whole minor mode, if you don't even need/want it. Or, if you want to keep it, at least you'll know in what key map to change the binding, instead of `racket-repl-mode-map`.

Does this help?

**Comment by greghendershott** [comment]
I only skimmed it but this seems maybe useful: https://github.com/syl20bnr/spacemacs/issues/5933 ?

**Comment by cflewis** [comment]
For people arriving here via Google:

Here is what I found using `describe-key` (SPC-SPC-describe-key in Spacemacs).

```text
C-j runs the command comint-next-input, which is an interactive compiled Lisp
function in ‘comint.el’.

It is bound to C-j, <C-down>, <normal-state> C-j, <insert-state> <down>,
<insert-state> C-j, M-n, <menu-bar> <inout> <next-history>.

(comint-next-input ARG)

Cycle forwards through input history.
```

Weirdly, although `describe-key` for `C-j` says it's for evil mode, it doesn't seem to be, it still cycles the history, so I guess it's also comint.

So that's tricky! http://ergoemacs.org/emacs/reclaim_keybindings.html told me to look at the `comint.el` source to find the map.

I attempted

```elisp
  (add-hook 'comint-mode-hook
          (lambda ()
            (define-key comint-mode-map (kbd "C-j") #'evil-window-down)
            (define-key comint-mode-map (kbd "C-k") #'evil-window-up)))
```

with no luck.

```elisp
  (add-hook 'comint-mode-hook (lambda () (define-key comint-mode-map "C-j" #'evil-window-down)))
```

was my other attempt, same failure. Attempts to set other keys unused by comint but by evil (C-t) also failed. My suspicion is that something about REPL mode results in Spacemacs going back to some default configuration to avoid screwing up the "terminal" window. But anything that didn't clash is passed back; so "C-h" and "C-l", so oddly these work.

I have given up on this; I simply couldn't figure it out. I'm going to just use `SPC w + jk` and try to override my muscle memory. Or just have a wider window so that the REPL appears as a vsplit, so it uses the C-j and C-k instead :laughing: 

Thanks for all the help Greg, I really learnt a lot about Emacs today! I switched to Emacs after being die-hard Vim specifically for Racket mode. There is really no other editor that comes close to what you've done. I put something in the tip jar, have a coffee or two when we can go back to coffee shops :coffee:
