### ISSUE TITLE
browse-url doesn't handle URL anchors on macOS or Windows

### ISSUE THREAD

**Issue by sorawee** [greghendershott/racket-mode#476]
### Steps to reproduce:

1. Paste `#lang racket add1`
2. Move the point to `add1`
3. Run `racket-xp-documentation`

### Expected behavior:

A browser shows up with the documentation

### Actual behavior

No browser shows up.

### Discussion

The problem is that the doc URL, such as `file:///Applications/Racket v7.7/doc/reference/generic-numbers.html#(def._((quote._~23~25kernel)._add1))`, has `file://` with an anchor (`#`). To quote https://www.emacswiki.org/emacs/BrowseUrl#toc23:

> Rather, it seems to be the case that `file:///C:/index.html#test` is a nonstandard URI; RFC 1630 and RFC 1738 don’t specify a `#target` (i.e., an anchor) for file URIs. (External URIs work!) Most browsers will happily parse such URIs anyway, but with Window’s `ShellExecute` the nonstandard URI is converted to a standard one before reaching the browser, and so the `#target` is stripped off.

The same problem happens in Mac. In particular, `browse-url` uses `open` to open files, and `open` has this very limitation.

This issue also came up at https://github.com/dash-docs-el/helm-dash/issues/36 and https://apple.stackexchange.com/questions/194501/open-a-file-url-with-anchor-from-terminal.

My workaround for now is to do the following:

```
  (defun my-browse-url (url &optional new-window)
    (interactive (browse-url-interactive-arg "URL: "))
    (start-process "chrome" nil "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" url))
  (setq browse-url-browser-function 'my-browse-url)
```

<details>
```
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
                 (20200526 1552)
                 "Racket editing, REPL, and more"
                 ((emacs
                   (25 1))
                  (faceup
                   (0 0 2))
                  (pos-tip
                   (20191127 1028)))
                 nil nil "/Users/sorawee/.emacs.d/elpa/26.3/develop/racket-mode-20200526.1552"
                 ((:url . "https://www.racket-mode.com/")
                  (:maintainer "Greg Hendershott")
                  (:authors
                   ("Greg Hendershott"))
                  (:commit . "29afd2544a2f14bf29f3e542f6177579d0ae581f"))
                 nil))
((emacs-version "26.3")
 (system-type darwin)
 (x-gtk-use-system-tooltips UNDEFINED)
 (major-mode racket-mode)
 (racket--el-source-dir "/Users/sorawee/.emacs.d/elpa/26.3/develop/racket-mode-20200526.1552/")
 (racket--rkt-source-dir "/Users/sorawee/.emacs.d/elpa/26.3/develop/racket-mode-20200526.1552/racket/")
 (racket-program "racket")
 (racket-command-timeout 10)
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function nil)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "open")
 (racket-images-system-viewer "open")
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-pos-tip)))
(enabled-minor-modes
 (Info-breadcrumbs-in-mode-line-mode)
 (anzu-mode)
 (async-bytecomp-package-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-highlight-symbol-mode)
 (auto-save-mode)
 (bug-reference-prog-mode)
 (centaur-tabs-mode)
 (clean-aindent-mode)
 (column-number-mode)
 (company-mode)
 (company-statistics-mode)
 (counsel-mode)
 (electric-indent-mode)
 (eval-sexp-fu-flash-mode)
 (evil-local-mode)
 (evil-mc-mode)
 (evil-mode)
 (evil-surround-mode)
 (eyebrowse-mode)
 (fci-mode)
 (file-name-shadow-mode)
 (flycheck-pos-tip-mode)
 (font-lock-mode)
 (global-anzu-mode)
 (global-auto-revert-mode)
 (global-company-mode)
 (global-eldoc-mode)
 (global-evil-surround-mode)
 (global-flycheck-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-git-gutter+-mode)
 (global-hl-line-mode)
 (global-hl-todo-mode)
 (global-page-break-lines-mode)
 (global-spacemacs-leader-override-mode)
 (global-spacemacs-whitespace-cleanup-mode)
 (global-undo-tree-mode)
 (global-vi-tilde-fringe-mode)
 (goto-address-prog-mode)
 (highlight-numbers-mode)
 (highlight-parentheses-mode)
 (hl-todo-mode)
 (hs-minor-mode)
 (hybrid-mode)
 (ido-vertical-mode)
 (indent-guide-global-mode)
 (indent-guide-mode)
 (ivy-mode)
 (line-number-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (nyan-mode)
 (override-global-mode)
 (persp-mode)
 (projectile-mode)
 (pupo-mode)
 (purpose-mode)
 (racket-xp-mode)
 (rainbow-delimiters-mode)
 (ranger-override-dired-mode)
 (recentf-mode)
 (save-place-mode)
 (savehist-mode)
 (shell-dirtrack-mode)
 (show-smartparens-global-mode)
 (show-smartparens-mode)
 (smartparens-global-mode)
 (smartparens-mode)
 (spacemacs-leader-override-mode)
 (spacemacs-whitespace-cleanup-mode)
 (transient-mark-mode)
 (undo-tree-mode)
 (vi-tilde-fringe-mode)
 (which-key-mode)
 (winner-mode)
 (winum-mode)
 (ws-butler-global-mode)
 (ws-butler-mode)
 (xterm-mouse-mode)
 (yas-global-mode)
 (yas-minor-mode))
(disabled-minor-modes
 (Info-persist-history-mode)
 (abbrev-mode)
 (auto-compile-mode)
 (auto-compile-on-load-mode)
 (auto-compile-on-save-mode)
 (auto-fill-function)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (blink-cursor-mode)
 (buffer-read-only)
 (bug-reference-mode)
 (centaur-tabs-local-mode)
 (cl-old-struct-compat-mode)
 (company-search-mode)
 (compilation-in-progress)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (defining-kbd-macro)
 (delete-selection-mode)
 (dired-hide-details-mode)
 (display-line-numbers-mode)
 (edebug-mode)
 (editorconfig-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-pair-mode)
 (electric-quote-mode)
 (elisp-slime-nav-mode)
 (evil-matchit-mode)
 (flycheck-mode)
 (flyspell-mode)
 (geben-full-frame-mode)
 (geben-mode)
 (git-commit-mode)
 (git-gutter+-mode)
 (global-auto-highlight-symbol-mode)
 (global-display-line-numbers-mode)
 (global-evil-matchit-mode)
 (global-evil-mc-mode)
 (global-highlight-parentheses-mode)
 (global-prettify-symbols-mode)
 (global-reveal-mode)
 (global-visual-line-mode)
 (goto-address-mode)
 (hidden-mode-line-mode)
 (hl-line-mode)
 (horizontal-scroll-bar-mode)
 (ibuffer-auto-mode)
 (ido-everywhere)
 (imenu-list-minor-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (mail-abbrevs-mode)
 (mml-mode)
 (next-error-follow-minor-mode)
 (outline-minor-mode)
 (overseer-mode)
 (overwrite-mode)
 (page-break-lines-mode)
 (paragraph-indent-minor-mode)
 (popwin-mode)
 (prettify-symbols-mode)
 (racket-smart-open-bracket-mode)
 (rectangle-mark-mode)
 (reveal-mode)
 (server-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (size-indication-mode)
 (smartparens-global-strict-mode)
 (smartparens-strict-mode)
 (spaceline-helm-mode)
 (spaceline-info-mode)
 (symbol-overlay-mode)
 (temp-buffer-resize-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-resume-mode)
 (undo-tree-visualizer-selection-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode)
 (with-editor-mode)
 (xref-etags-mode))
```
</details>

**Comment by greghendershott** [comment]
I'm conflicted about this.

- On the one hand, in general I want Racket Mode to "just work". In the past, I tried to handle this, and [shared some code to make it work better in `net/sendurl`](https://github.com/rrthomas/racket/commit/f175148ca3d26e97d4b68df9f73d693a0ae74243#diff-fb22a7ea6371fd000969881685e56e6d). But in commit c88a12a a few months ago I stopped doing this in Racket Mode. Because...

- On the other hand, I think a more-accurate title for this issue would be that Emacs' `browse-url` in general does not always handle anchors in URLs -- and IIUC [the reason is actually "because security" on some operating systems](https://www.greghendershott.com/2017/03/please-scroll.html). It's a problem that really ought to be fixed (if possible) in `browse-url` -- or at least in an Emacs package dedicated to this (maybe in a similar spirit to the `exec-path-from-shell` package?).

   I briefly thought of making such a new package, but I feel like I already have my hands full.

**Comment by alex-hhh** [comment]
This is also a problem on Windows and I solved it using an idea from [this StackOverflow question](https://stackoverflow.com/questions/300509/how-to-launch-a-file-protocol-url-with-an-anchor-from-java).

Basically, I implemented my own `racket-browse-url` as follows:

```elisp
(defun racket-browse-url (url)
  (let* ((url (if (string-match ".*://" url) url (concat "file://" url)))
         (content (format "<html><head><meta http-equiv=\"refresh\" content=\"0;url=%s\" /></head></html>" url))
         (file (make-temp-file "racket-doc" nil ".html" content)))
    (browse-url file)))
```

And used this function in `racket-xp-documentation` instead of calling `browse-url` directly.

The only problem is that this creates a lot of small temporary files, but I can live with that.

**Comment by greghendershott** [comment]
@alex-hhh Thanks for sharing that it is also a problem on Windows.

This nudges me toward getting back into the "fixing `browse-url`" business again. Reluctantly. But if out-of-box people can't see docs well, on 2 of 3 platforms....

Proposal:

- Add a function similar to your `racket-browse-url`. (I _might_ just enhance it slightly to delete the temporary files using an Emacs idle timer, and also on the kill Emacs hook. (I don't know if browsers put `file:` pages in their own cache, and how eagerly they could be deleted.))

- Add a customizable variable, `racket-mode-browse-url-function`. Defaults to `racket-browse-url`. But people could set to plain old `browse-url-function` or to their own personal flavor (e.g. if this had existed you could have tweaked this without needing to fork/tweak `racket-xp-documentation`).

Maybe I would address this when looking at PR #462.

**Comment by sorawee** [comment]
Does the temp file need to have a unique name? Can't we just find a canonical name for this file, and concatenate it with `temporary-file-directory`? Then, there wouldn't be many temporary files, and we don't even need to clean them up.

**Comment by greghendershott** [comment]
> Can't we just find a canonical name for this file

Probably. The characters in a URL aren't necessarily valid for a file name in every given OS/filesystem. Do you already know how we would "just" handle this? :smile: base64?

**Comment by alex-hhh** [comment]
On my machine, `browse-url` returns before the browser opens the file and it takes about 2-3 seconds for the browser window or new tab to appear.   This means that:

* the temporary file cannot be deleted immediately after `browse-url` returns -- I tried, and Firefox failed to find it.
* it might be possible to send a second `browse-url` request before the first one finishes -- not sure how important this case would be, but calling `racket-xp-documentation` in quick succession on two different functions would cause only the second function to have its documentation shown in the browser.

In any case, if you want a single temporary file, the call to `make-temp-file` returns the file name, and new contents can be written to it using `write-region`, so this temporary file can be re-used.

**Comment by sorawee** [comment]
Oh, what I suggested was that we come up with a name, like `racket-mode-docs.html`. I do hope this is a valid filename on every filesystem. Then, write the file to `(concat temporary-file-directory "racket-mode-docs.html")`.

**Comment by greghendershott** [comment]
@alex-hhh Thanks for the information! I wasn't clear before but I imagined cleaning temp files after they're "old enough" (say, an hour) and doing that age check on an idle timer. (Definitely not "delete all the temp files as soon as Emacs idle timer goes off".)

Anyway I wouldn't try to be too clever, and I'd want to err on the side of leaving behind too many, too long.

In fact, I don't know, what you're doing is already good. Maybe I shouldn't even try to "improve" it, at all.

---

@sorawee I thought the idea was to make a temporary HTML file to do the redirect to each requested URL -- including the specific anchor link in the file. I think that means 1 temp file per unique full URL?

Two random examples of same file, different anchors within:

- `file:///home/greg/racket/7.7/doc/data/interval-map.html#(def._((lib._data/interval-map..rkt)._interval-map-ref))`
- `file:///home/greg/racket/7.7/doc/data/interval-map.html#(def._((lib._data/interval-map..rkt)._make-interval-map))`

That's why I was concerned, are those valid file names on all filesystems.

I suppose it's possible to make anything work, eventually, but I'm leaning toward letting a "make temporary file with a valid name" function handle this problem.

**Comment by sorawee** [comment]
Sorry for not being clear.

> I thought the idea was to make a temporary HTML file to do the redirect to each requested URL -- including the specific anchor link in the file. 

Yep, I agree with all of this.

> I think that means 1 temp file per unique full URL?

This is the assumption that I am challenging. Can't we use one filename for every URL? Like `racket-mode-docs.html`.

Each time `racket-xp-documentation` is called, either create or overwrite the existing `racket-mode-docs.html` and there's no need to clean the file up. 

1. Since we did not clean up the file, there's no problem with "the temporary file cannot be deleted immediately after browse-url returns -- I tried, and Firefox failed to find it."
2. But because we reuse the same file, there's no problem with "this creates a lot of small temporary files".

**Comment by greghendershott** [comment]
@sorawee Oh, now I understand what you meant.

One gotcha could be "concurrency" edge cases like overlapping requets. @alex-hhh reported a 2-3 second delay (and that's with both the browser and the Racket Mode back end already running, IIUC). Maybe it's unlikely a user would <kbd>C-c C-d</kbd> two different things (and URLs) that quickly, but....

**Comment by greghendershott** [comment]
I pushed a commit implementing the approach I outlined, including using the temp file trampoline that @alex-hhh supplied. (I did need to tweak that because `make-temp-file` lacks the "contents" final argument in Emacs 25.2. I'm not sure exactly when it was added, but it's easy enough to use `write-region` in a separate step, regardless.)

If either of you has a chance to review and offer feedback, I'd welcome it. Otherwise I'll probably merge this to `master` within a few days. I might rewrite some of the doc prose after re-reading it with a fresh brain, later.

**Comment by sorawee** [comment]
Confirm working on Mac.

**Comment by alex-hhh** [comment]
I tried it out on Windows, and it works as well.

**Comment by sorawee** [comment]
Thank you!
