### ISSUE TITLE
Better evil-mode support on racket-mode repl?

### ISSUE THREAD

**Issue by sunchaesk** [greghendershott/racket-mode#489]
I think it would be great to have better evil mode support for the racket-mode repl. Switch between normal mode, insert mode, visual mode, etc works well on the repl already, but there are some features that don't work.
Most notably, C-w stuff doesn't work. C-w q to close the window or C-w w to switch to other windows doesn't work.

**Comment by greghendershott** [comment]
I agree this would be nice. Unfortunately I'm not an evil-mode user and don't know very much about it (yet).

A couple quick things:

- `racket-repl-mode` is derived from `comint-mode` -- much like `shell-mode`. If you `M-x shell`, in that buffer do these <kbd>C-w</kbd> commands work?

- Although `racket-repl-mode-map` binds <kbd>C-w</kbd> to `comint-kill-region` by default, my understanding is that keybindings of minor modes (like `evil-mode`) take precedence over the major mode's map, so I'm confused what's happening.

    Anyway, I wonder, if you add a `racket-repl-mode-hook` and explicitly `(define-key racket-repl-mode-map "C-w" evil-window-map)`, does it then work for you? (I'm just guessing from a shallow glance at evil source code.)

**Comment by sunchaesk** [comment]
Thanks I will add the hook to my config.

`C-w` seems to work fine when I use `M-x shell` so it is definitely weird. I am using doom emacs at the moment and maybe that has to do something with it?

**Comment by tgbugs** [comment]
Here is how I handle the `C-w` issue and also fix issues with `C-x C-e`.
`racket-mode` rebinds `C-w` so when you start it the evil binding is superseded. All you need to do is unbind it from `racket-mode-map`. Not that you have to load `racket-repl` so that `racket-repl-mode-map` exists so that you can unbind `C-w` there as well.

```elisp
(use-package racket-mode
  :commands racket-repl  ; required for racket-repl-mode-map to load so we can fix it
  :bind (:map racket-mode-map
              ("C-w")  ; unbind default emacs C-w behavior which is set again by racket-mode
              :map racket-repl-mode-map
              ("C-w"))
  :config
  ;; fix evil-eol
  (defun evil-eol-racket-send-last-sexp (command &rest args)
    "In normal-state or motion-state, last sexp ends at point."
    (if (and (not evil-move-beyond-eol) (or (evil-normal-state-p) (evil-motion-state-p)))
        (if (or (eobp) (eolp))
            (apply command args)
          (save-excursion
            (forward-char)
            (apply command args)))
      (apply command args)))
  (unless (and (boundp 'evil-move-beyond-eol) evil-move-beyond-eol)
    (advice-add 'racket-send-last-sexp
                :around 'evil-eol-racket-send-last-sexp)))
```

**Comment by greghendershott** [comment]
@tgbugs Thanks for chiming in with this advice!

I'm still confused how/why the `racket-repl-mode-map`, a major mode key map, would take precedence over evil-mode's, a minor-mode map. I was the under the impression that minor modes win. But I'm glad this work-around works for you!

---

p.s. About this:

```elisp
:commands racket-repl  ; required for racket-repl-mode-map to load so we can fix it
```

If you find that annoying -- actually doing the `racket-repl` command -- I think something like this might work instead?

```elisp
:init (require 'racket-repl-mode) ;load racket-repl-mode so we can change racket-repl-mode-map
```

**Comment by tgbugs** [comment]
Hrm, a good point. The `C-w` issue might be peculiar to my config because I unblind `C-w` globally before rebinding my own `C-w` prefixed commands globally and also unbind it in insert mode because evil-mode has it bound to something that I did not want. That would mean that there isn't anything in the minor mode binding to override it. However, if someone is in insert mode in the repl, then `C-w` won't work since it is bound to `evil-delete-backward-word` and not as a prefix for changing windows. Not sure if that is that is causing the original issue though.

Re the `:commands`. Ah yes, for others it is a good note that one can probably require rrm as you suggest (I haven't tested it but I don't see why it would not work). I don't mind it in my config since I run the deamon and it reduces the wait time the first time I need to run a racket buffer. In the doom use case that is likely not what people want.
