### ISSUE TITLE
raco test racket/scribble.rkt failing in chroot

### ISSUE THREAD

**Issue by bremner** [greghendershott/racket-mode#513]
Sorry I can't provide the output from racket-bug-report, racket-mode is not installed in this chroot. I'm trying to run the tests, but I'm getting some failures I don't understand.  Probably I'm missing some dependency in the chroot, but I don't know what.
```
(unstable-amd64-sbuild)bremner@convex:~/racket-mode$ raco test racket/scribble.rkt 
raco test: (submod "racket/scribble.rkt" test)
--------------------
procedure
FAILURE
name:       check-not-false
location:   scribble.rkt:82:4
params:     '(#f)
--------------------
--------------------
syntax
FAILURE
name:       check-not-false
location:   scribble.rkt:84:4
params:     '(#f)
--------------------
--------------------
parameter
FAILURE
name:       check-not-false
location:   scribble.rkt:86:4
params:     '(#f)
--------------------
--------------------
indented sub-item
FAILURE
name:       check-not-false
location:   scribble.rkt:88:4
params:     '(#f)
--------------------
--------------------
1 of 2
FAILURE
name:       check-not-false
location:   scribble.rkt:91:6
params:     '(#f)
--------------------
--------------------
2 of 2
FAILURE
name:       check-not-false
location:   scribble.rkt:93:6
params:     '(#f)
--------------------
--------------------
FAILURE
name:       check-not-false
location:   scribble.rkt:94:2
params:     '(#f)
--------------------
--------------------
FAILURE
name:       check-equal?
location:   scribble.rkt:244:4
actual:     #f
expected:   "(list v ...) -> list?\n  v : any/c"
--------------------
8/11 test failures
```

**Comment by greghendershott** [comment]
The tests exercise Racket Mode's ability to use Racket's `scribble/xref` and `setup/xref modules` -- functions like [`load-collections-xref`](https://docs.racket-lang.org/raco/xref.html#%28def._%28%28lib._setup%2Fxref..rkt%29._load-collections-xref%29%29),  [`xref-binding->definition-tag`](https://docs.racket-lang.org/scribble/xref.html#%28def._%28%28lib._scribble%2Fxref..rkt%29._xref-binding-~3edefinition-tag%29%29), and [`xref-tag->path+anchor`](https://docs.racket-lang.org/scribble/xref.html#%28def._%28%28lib._scribble%2Fxref..rkt%29._xref-tag-~3epath%2Banchor%29%29) -- to find a local `.html` file containing documentation for an identifier.

(Other code in that `scribble.rkt` file tries to extract bits of the HTML for presentation in `racket-describe-mode` --- but the failing tests don't exercise any of that.)

So it sounds like your installation of Racket is lacking installed documentation. And/or the xref functions are unable to find any docs -- not even for basic identifiers like `print` from `racket/base`.

IIRC Racket uses a sqlite database for the xref info, which could be another point of failure.

One sanity check: What happens if you try `raco doc print` at the command line? I think that mostly exercises the same things?

**Comment by greghendershott** [comment]
Actually `raco doc print` would do a search for the string `"print"` -- not a search for the imported `print` _identifier_. So that exercises different things, and doesn't necessarily "prove" anything, if it does work or not. But it still might be an interesting quick sanity check to try.

**Comment by greghendershott** [comment]
For Racket Mode's back end Racket code to work, generally the simplest thing is to install full Racket, or install Minimal Racket but also do `raco pkg install drracket`. That is somewhat "heavier" than necessary -- I have an open issue #471 for that -- but it's safe.

**Comment by bremner** [comment]
Indeed I was missing the documentation (because of the split in debian). Thanks for your help. With the docs installed it works fine.
