### ISSUE TITLE
Add sending scribbles and infix to REPL

### ISSUE THREAD

**Issue by Nathan-Furnal** [greghendershott/racket-mode#531]
Hi there, 

Today I ran into an issue, I was trying to eval a scribble as well as an infix with `C-x C-e` but it didn't work as intended and I had to send the region to the REPL instead. I wonder if you'd be ok to make sending scribble and infix to the REPL with `C-x C-e`? I looked up the code and it seems that `racket--repl-last-sexp-start` is responsible for doing that. I don't know much ELisp but it seems that you're already looking at what happens before the point when evaluating comments, which could be extended to match `@` or `$` I believe.

I'm just getting started with Racket so I don't know if that question makes much sense? 

Thanks for the great mode, 

Nathan

**Comment by greghendershott** [comment]
Hi.

Can you give some examples of what you mean by "a scribble"?

And also examples of "an infix"?

---

<kbd>C-x C-e</kbd> is bound to `racket-send-last-sexp`. It sends the previous s-expression to the REPL. An s-expression in a lisp like Racket is (approximately) a single thing like a number or string, or, a parenthesized lists of such things.

That's why I'm curious to see examples of expressions you want to send to the REPL. Maybe they're also s-expressions and there's a bug to fix. Or if they're not, then it's a question of whether to bend the existing command to do more than it says, or, add new commands, or some other idea I don't know yet.

**Comment by sorawee** [comment]
@greghendershott I believe this is the same question as https://www.reddit.com/r/Racket/comments/mvkm59/is_there_a_way_to_eval_infix_expressions_in/. That is, @Nathan-Furnal probably meant to say at-exp notation, not infix notation.

**Comment by greghendershott** [comment]
Ah OK. (I wasn't trying to be picky about the terminology. I was just too dense to guess.)

I see what you mean about at-expressions a.k.a. at-exps like
- `@+[1 2]`
- `@string-append["foo"]{bar}`.
-  Of course, the at-exp `@(+ 1 2)` does work. :)

@sorawee 's code looks good:

```elisp
(defun racket--repl-find-at-exp-beg ()
  (save-excursion
    (condition-case ()
        (progn
          (backward-sexp)
          (if (cond
               ((save-match-data (looking-at "{"))
                (backward-sexp)
                (if (save-match-data (looking-at "\\["))
                    (progn
                      (backward-sexp)
                      (save-match-data (looking-at "@")))
                  nil))
               ((save-match-data (looking-at "\\["))
                (backward-sexp)
                (save-match-data (looking-at "@")))
               (t t))
              (point)
            (scan-error (user-error "There isn't a complete @-expression before point"))))
      (scan-error (user-error "There isn't a complete s-expression before point")))))

(defun racket-send-last-at-exp ()
  (interactive)
  (racket--send-region-to-repl (racket--repl-find-at-exp-beg)
                               (point)))
```

---

I'm not sure what to do. Some choices:

1. The "ultimately correct/perfect" thing, probably: Racket should allow languages (like `scribble`) -- and even meta-languages (like `at-exp`) -- to communicate their notion of a "complete-enough expression to send to a REPL". And Racket Mode would passively use that, and not try to be clever.

2. Add @sorawee 's `racket-send-last-at-exp` to Racket Mode, too.  Maybe change the default binding of <kbd>C-x C-e</kbd> to that. Of course users could bind it differently, including to the plain sexp function which would still remain.

3. None of the above. Let people do their own customization, if they want. 

I could justify 3 because we should wait for 1 someday; and anyway sending to the REPL is just "select/copy/paste by other means". I don't know if that's wise or lazy.

Maybe 2 is the practical warm bowl of porridge.

**Comment by sorawee** [comment]
Oh, actually I forgot to handle this case:

```
@~a{abc}
```

**Comment by greghendershott** [comment]
Hmm drracket does have a "submit predicate". I wonder how that works with at-expressions generally, and with meta langs like `at-exp`.

**Comment by greghendershott** [comment]
(Racket Mode does use this when available to decide when pressing ENTER in the REPL should submit it. I wonder if it could be used somehow, for determining an expression to send, from a source buffer.

It's definitely not i_ntended_ to be used like that. Matthias hates the concept of send to REPL. :smile: Seriously, it opens the door to the REPL becoming out of sync with the source file. But, being able to type things at the REPL, is also such a way. Or copy and paste them. It's about convenience.)

**Comment by greghendershott** [comment]
A few days ago I noticed this had fallen by the wayside. Sorry! I did just merge a commit for this.
