### ISSUE TITLE
Looks like racket-mode installation has a bug

### ISSUE THREAD

**Issue by kyp0717** [greghendershott/racket-mode#548]
When trying to install racket-mode package, I get the following error ...
```
Debugger entered--Lisp error: (error "Need package `pos-tip-20191127.1028', but only 201...")
  error("Need package `%s-%s', but only %s is available" pos-tip "20191127.1028" "20140613.924")
  package-compute-transaction((#s(package-desc :name racket-mode :version (20210702 1906) :summary "Racket editing, REPL, and more" :reqs ((emacs (25 1)) (faceup (0 0 2)) (pos-tip (20191127 1028))) :kind tar :archive "melpa" :dir nil :extras ((:commit . "54bc174cc4ee16db7383f33965344947e24a34c0") (:authors ("Greg Hendershott")) (:maintainer "Greg Hendershott") (:url . "https://www.racket-mode.com/")) :signed nil)) ((emacs (25 1)) (faceup (0 0 2)) (pos-tip (20191127 1028))) (#s(package-desc :name racket-mode :version (20210702 1906) :summary "Racket editing, REPL, and more" :reqs ((emacs (25 1)) (faceup (0 0 2)) (pos-tip (20191127 1028))) :kind tar :archive "melpa" :dir nil :extras ((:commit . "54bc174cc4ee16db7383f33965344947e24a34c0") (:authors ("Greg Hendershott")) (:maintainer "Greg Hendershott") (:url . "https://www.racket-mode.com/")) :signed nil)))
  package-compute-transaction(nil ((racket-mode)))
  package-install(racket-mode)
```

Dependency error.  Need `20191127.1028` but version `20140613.924` was installed instead.  Maybe a problem with the pos-tip install and NOT racket-mode.

**Comment by greghendershott** [comment]
The currently available version of `pos-tip` appears to be `20191227.1356`  --- see https://melpa.org/#/pos-tip --- so, I'm not sure why your Emacs thinks the newest is `20140613.92` (these version numbers are datetimes, so that's from 2014!).

This doesn't seem to be a Racket Mode bug per se, but happy to help if I can.

Some maybe relevant questions:

- [ ] What version of Emacs are you using?
- [ ] What is your value for `package-archives`?
- [ ] Did you `M-x package-refresh-contents` before trying to install?

**Comment by kyp0717** [comment]
Thanks for looking into this.  I was building racket-mode inside docker container and it seems to be an issue with the container.   Upon reboot, the issue went away.  So sorry to bother you about this.  Thanks for checking in.  Thanks!

**Comment by kyp0717** [comment]
Issue resolve upon reboot!
