### ISSUE TITLE
How to configure the pathe where packages are loaded from?

### ISSUE THREAD

**Issue by a-berg** [greghendershott/racket-mode#550]
Hi, I have installed Racket on my machine and started using racket-mode, however the REPL doesn't seem to find packages. There is more info on my stackexchange question:

https://emacs.stackexchange.com/q/66655/30203

Basically, it boils down to:

>How to tell `racket-mode` to load Racket packages from $HOME/.local/share/racket/8.0/pkgs/ rather than $HOME/.racket/8.0/pkgs/?

**Comment by a-berg** [comment]
Basically I set the variable `PLTADDONDIR` to point to the directory I want to, then works. I would still like to know why Emacs loaded a different path than my terminal, so any help in that regard is welcome..

**Comment by greghendershott** [comment]
I don't have any hands-on experience using Guix or Nix. From seeing various things on the Racket mailing list or Slack, I get the impression there is some tension with the idea that `raco pkg` is responsible for installing Racket language packages -- but maybe I'm mistaken.

Since I don't have a clear picture of what's going wrong, and why, all I can think of right now is a couple factoids:

- There is an Emacs package `exec-path-from-shell` to ensure that the environment in Emacs matches that in the shell. I've only ever heard of people using this on macOS with GUI Emacs, because on macOS GUI apps don't inherit the shell env. I don't know but maybe that could also help here??

- Racket Mode uses a customization variable `racket-program`. By default in *nix it is `racket`, but you can set it to an absolute path instead. Again I don't really know, but maybe that could help here??

**Comment by greghendershott** [comment]
Did either of those ideas help?
