### ISSUE TITLE
eliminate the dependency of projectile or make it optional

### ISSUE THREAD

**Issue by capfredf** [greghendershott/racket-mode#557]
[I became aware of the dependency the other day when I was setting up borg to manage my emacs environment.]
racket-mode use functions provided by projectile in two places, which makes projectile a light dependency. This is not a problem, but Emacs does provide built-in project management probably since version 25 and it's been getting improved. (I've using the built-in `project` mode since I switched to the main branch of emacs as my daily driver). After a quick glance into the source code of `project.el`, it seems to me that racket-mode could replace calls to the `projectile-*` function with the corresponding `project-*` functions. 

Whether `project.el` in emacs 25, 26 or 27 provides the same or similar functions is still unknown to me. If it does not, we can still use projectile.   

@greghendershott  if the proposal looks to you, I will work on it (when I need some distractions from hacking typed racket).

**Comment by greghendershott** [comment]
Thanks, it would be great if you want to take a look sometime.

1. `projectile` is supposed to be optional, using `fboundp`.  It's not in `Package-Requires`. But if you're experiencing otherwise of course let's fix.

2. One of the spots already uses `project` (also optionally). The other, the "experimental" step debugger, doesn't. Maybe they should be consistent.

**Comment by greghendershott** [comment]
I refreshed my memory on `borg`. Maybe 1 is due to the Emacsmirror database reporting that projectile is a dependency? In [epkg.sql](https://github.com/emacsmirror/epkgs/blob/master/epkg.sql) I see `INSERT INTO required VALUES('"racket-mode"','projectile','t',NULL,NULL);`. But I didn't dig into why it does that. Do you want to?

(Rough guess: It doesn't trust `Package-Requires`, which is probably smart. Instead it does some analysis of the package code. If so, maybe it is understandably fooled in `racket-debug.el` by `(ignore-errors (require 'projecticle) ___)`. I don't recall why `fboundp` alone didn't suffice there.)

**Comment by capfredf** [comment]
I will take a look at why epkgs does that.

**Comment by capfredf** [comment]
@greghendershott BTW, can you assign this issue to me?

**Comment by greghendershott** [comment]
Speaking of `Package-Requires`, yesterday I merged commits 23be187 and 794f737 which eliminate `pos-tip` and `faceup` as hard dependencies for end users. Now [it's just](https://github.com/greghendershott/racket-mode/blob/master/racket-mode.el#L6):

```elisp
;; Package-Requires: ((emacs "25.1"))
```

There are zero dependencies on other Emacs packages.

The only requirement is that Emacs itself be version 25.1+.

---

For CI and for people hacking on Racket Mode, the `Makefile` target `deps` does install some packages needed for tests; `make deps` will `package-install` `faceup` and `paredit`. Of course that's N/A if instead of package.el you're using something like borg or straight.el.

**Comment by greghendershott** [comment]
I just wanted to touch base on this, is it still active?

If not I might do some new-year cleaning and close this.

Having said that I'm happy to leave this open if you think there is -- or even just _might_ be -- something to do on my end.

**Comment by capfredf** [comment]
Oops, I forgot I had this issue on my to-do list. I will get back to you asap

**Comment by capfredf** [comment]
Like you said, `epkg` tries its own approach to detect dependencies and I will post an issue/question there.

**Comment by greghendershott** [comment]
Thank you for offering to help. If you need to hand it back to me, just let me know.
