### ISSUE TITLE
Translate paths back-to-front when displaying documentation

### ISSUE THREAD

**Issue by fakedrake** [greghendershott/racket-mode#564]
When trying to describe a symbol, if the remote backend returns a path for racket-describe to render paths are not handled properly. The fix I did (but sadly am not in a position to push due to corporate firewalls) was to change [here](https://github.com/greghendershott/racket-mode/blob/rebased-multi-back-end/racket-describe.el#L91) :

```
             [...]
               (let ((back-path (racket-file-name-back-to-front path)))
                 (racket--describe-insert-dom pop-to-p
                                              back-path
                                              anchor
                                              (racket--doc-path->shr-dom back-path))))
              [...]
```
from

```
         (racket--describe-insert-dom pop-to-p
                                      path
                                      anchor
                                      (racket--doc-path->shr-dom path)))
```

**Comment by greghendershott** [comment]
Thanks, good catch.

I pushed a commit for this on the WIP topic branch `rebased-multi-back-end`.

I'm closing the issue because the CI failed only for [the one job testing against Racket snapshot, and the reason was a 403 for the Racket installer](https://github.com/greghendershott/racket-mode/runs/3803345415). Which can happen from time to time if a Racket snapshot build stalls or fails.
