### ISSUE TITLE
Evaluation Overlay

### ISSUE THREAD

**Issue by quangIO** [greghendershott/racket-mode#573]
I find the elisp evaluation overlay is quite nice. Geiser also supports this feature with geiser-mode-eval-last-sexp-to-buffer. Perhaps racket-mode can have it too.

(example implementation using eros from https://reddit.com/r/emacs/comments/nvhb82/comment/h13ug8i/)
```elisp
(defun racket-eros-eval-last-sexp ()
  "Eval the previous sexp asynchronously and create an eros overlay."
  (interactive)
  (unless (racket--repl-live-p)
    (user-error "No REPL session available."))
  (racket--cmd/async
   (racket--repl-session-id)
   `(eval ,(buffer-substring-no-properties (racket--repl-last-sexp-start) (point)))

   (lambda (result) (message "%s" result)
     (let ((point (point)))
       (eros--make-result-overlay result
         :where point
         :duration 10)))))
```

**Comment by quangIO** [comment]
I just tried to replace my `eros` setup with `racket-show-pseudo-tooltip` yesterday. Now I see your branch issue-573, I just use it and remove `eros` 👍 . I find it wonderful so far. Thanks! 

One eros's advantage is the ability to config display duration, but I don't miss it. For larger values, I also find using `posframe-show` could achieve a nicer UX (pos-tip doesn't work well on MacOS I think). But in the end, I just keep `racket-show-pseudo-tooltip` as it works well enough for me.

**Comment by greghendershott** [comment]
Great!

Yes, I was going to comment here, but you noticed my work-in-progress. :smile:

The missing piece I realized, when I tried it myself, was that the pseudo-tooltip needed some way to disappear, whether via a timer or a pre-command-hook. (That's been N/A for the sole use of `racket-show`, to-date, by `racket-xp-mode`, because it was updating upon any point motion.) So I needed to add "transient-p" argument to `racket-show` for this.

I also had a bunch of commits from some months ago, on a (now merged/gone) branch `issue-514`, that improved `racket-pseudo-tooltip`. This was a good opportunity to merge those.

And as I looked at the code with fresh eyes, I saw some comments and doc strings and other details that could be improved.

But having said all that the change to `racket-eval-last-sexp` itself was about as small as we discussed, and most of the other changes were nice-to-have not must-have.

---

I may fiddle a bit more but hopefully not and I'd like to merge `issue-573` for real, soon, maybe later today.
