### ISSUE TITLE
Please consider removing define-obsolete-face-alias

### ISSUE THREAD

**Issue by bhrgunatha** [greghendershott/racket-mode#583]
`define-obsolete-face-alias` may seem like a good idea, but the problem with obsoleting a face defined for sole use in `racket-mode` to an existing emacs face has an unexpected result. 

I set a colour in my config for `racket-selfeval-face` because I liked constants to stand out visually. I  recently updated `racket-mode` and started to discover strange behaviour. After using `racket mode` - all other modes that use `font-lock-constant-face` now display using the colour I assigned to `racket-selfeval-face`. 

It took me quite a while to track down the culprit and reason for this unexpected issue. I suspect the purpose of `define-obsolete-face-alias` is to "re-direct" face definitions to other faces that you or your project defined, rather than standard emacs faces. 

[Quick link to racket-custom.el's usage](https://github.com/greghendershott/racket-mode/blob/master/racket-custom.el#L579)

**Comment by greghendershott** [comment]
Oh! I'm sorry this turned out to be so confusing and frustrating, due to me misunderstanding `define-obsolete-face-alias`.

[I didn't appreciate that it would be a full, "two-way" alias. Somehow I believed it would be more like a warning, "Hey this face is obsolete, and you should update your config, but meanwhile I'll helpfully use this other face instead." I'd used it some years ago for a `racket-paren-face`, with no reported problems for that, which contributed to me having a false confidence it was the right thing to do.]

What I wanted to avoid was just removing the definition entirely, and causing some breakage that way.

So I think probably I should keep the `defface` but explain the obsolescence in the doc string?

For example:

```diff
@@ -576,11 +576,18 @@ ignore POS. Examples: `racket-show-echo-area' and
-(define-obsolete-face-alias 'racket-paren-face 'paren-face
-  "2017-06-13")
+(defface racket-paren-face nil
+  "This face is unused since 2017-06-13.
+
+Instead customize the face `paren-face', which is provided by the
+optional package `paren-face'.")
 
-(define-obsolete-face-alias 'racket-selfeval-face 'font-lock-constant-face
-  "2021-10-20")
+(defface racket-selfeval-face nil
+  "This face is unused since 2021-10-20.
+
+Instead customize the face `font-lock-constant-face'.")
```

If (based on your unfortunate recent research) you have any thoughts about this, please let let me know. Otherwise I'll plan to merge a commit like that.

**Comment by bhrgunatha** [comment]
In fact I've removed my setting now but I thought it was worth documenting in case someone else had a similar problem. I guess no-one else **was** setting that face (or the older paren face you mention). I'm the one they mean when they say _"there's always one, isn't there?"_  :)

Thanks for your continuous work on racket-mode. Not sure what positive feedback you get but it really makes writing racket code **so** much nicer than the alternatives - since we can just use emacs.

**Comment by greghendershott** [comment]
Thank you for the kind words!

I merged this change.
