### ISSUE TITLE
Indentation rules for `def*` pattern apply in `contract-out`, and possibly other subforms

### ISSUE THREAD

**Issue by zyrolasting** [greghendershott/racket-mode#591]
There has been no change in my `racket-mode` configuration since #585. I am using whatever the default indentation settings happen to be.

Paste this code into a new `racket-mode` buffer. Select all code, then hit TAB to reindent.

```
(contract-out
 [d
  ()]
 [de
  ()]
 [def
  ()])
```

The empty list under `def` moves forward by one character. I expect that this relates to indentation rules for `define`-like forms.

```
(contract-out
 [d
  ()]
 [de
  ()]
 [def
   ()])
```

**Comment by greghendershott** [comment]
Unfortunately this is due to the `^def*` regexp nature of the matching. It has worked this way "forever" in Racket Mode. Dr Racket behaves the same, as it uses a similar pattern style.

A variation on this is `^with-*`.

---

Although I can imagine mitigations -- change the pattern to something like `^(def*`? -- they might be imperfect or even cause new problems.

Ultimately probably the only "perfect" solution would be for Racket macros to be able to specify their own indent, and for tools like Dr Racket and Racket Mode to utilize that.

So... I'm not sure what to do about this. Apply a band-aid, and possibly more band-aids for the band-aids? Or, accept the imperfection for now, and fix someday using some whole other better method?  I'm leaning toward the latter, but I don't know how annoying you find this.

**Comment by zyrolasting** [comment]
This is not painful enough for me to push the issue, so it's fine if y'all want to close this out.

I didn't have the context for why indentation worked the way it did, so thanks for sharing it. I figured if regular expressions appeared, they would apply to atomic elements of S-expressions, as opposed to lines.

I wonder if there is an approach that deconstructs an S-expression, only to rearrange the elements within a "template" of updated whitespace.

I can't give you a timeline, but if I showed you a proof of concept of what I'm talking about, would there be a path to including that approach in the source?

**Comment by greghendershott** [comment]
>  I figured if regular expressions appeared, they would apply to atomic elements of S-expressions, and would not allow for open brackets in the pattern.

I'm not sure what you mean here? Are you referring to my hypothetical "fix" of changing the pattern from `^def*` to something like `^(def*`?

> I wonder if there is an approach that deconstructs an S-expression, only to rearrange the elements within a "template" of updated whitespace. Is that basically what you are doing now? If not, is there room for a proof of concept of what I'm talking about?

- How it works now is basically the traditional Emacs way for lisps. Macro uses may have a certain number of "distinguished" "arguments", which, if not on the first line, get a special amount of indent compared to arguments to actual procedures. The number varies by special form. For nearly all macros, just supplying that number suffices. But as a fallback, it can also be a function. The matching to find a rule is done by simply looking at the macro name i.e. first symbol after an opening delimiter.

- How it works on the `hash-lang` branch is that Racket Mode completely defers all this to a `#lang`-supplied `drracket:indentation` function. The lang is 100% in control: "Here is a line of text, give me the indent amount" (plus a region/lines flavor). This is an improvement but only for macros the `#lang` handles this way (not other, individual macros).

- Racket currently has no way for individual macros definitions to specify they be indented in a certain style. I think making such a "protocol" and using it in tools like Racket Mode is the best way to go. Mostly I'd rather spend time on that sort of approach, than on handling it in Emacs with the current or new approaches?

**Comment by greghendershott** [comment]
I have a commit 59a0f25 which improves the documentation about this.

The commit message tags this issue to be closed when I merge the commit, because you had said:

> This is not painful enough for me to push the issue, so it's fine if y'all want to close this out.

---

Having said that, it occurs to me I could add some customization variable for this.

For example, `racket-indent-regexps` (or some better name) which defaults to true -- but if you or someone set it to false, it would not do these automatic indents of forms matching `^begin`, `^def` or `^with-`.

If that appeals, please let me know?

Otherwise I'll just merge and let the commit close this issue. (In that case, I guess I could add a new, feature-request issue for the customization variable... and wait to see if anyone chimes in that they really want that.)

**Comment by zyrolasting** [comment]
This sounds reasonable. Thank you so much for doing this!
