### ISSUE TITLE
Question on REPL name change

### ISSUE THREAD

**Issue by bhrgunatha** [greghendershott/racket-mode#593]
How do I find some racket repl buffer (in elisp) when the current buffer isn't linked to a racket file?  

The repl name has changed to `*Racket REPL </>*` when previously it was just `*Racket REPL*`?

I rely on finding the name `*Racket REPL*` in some elisp functions when I am not visiting a racket file. 
Can I rely on finding a `*Racket REPL </>*` or will that name vary for some reason?

**Comment by greghendershott** [comment]
If you mean for your personal use, then probably it is fine to just test for `*Racket REPL </>*` now instead.

---

The longer story is that there can be zero more REPL buffers, whose names are controlled by the value of the customization variable [`racket-repl-buffer-name-function`](https://www.racket-mode.com/#racket_002drepl_002dbuffer_002dname_002dfunction), which is a function that picks the name.

The default is [`racket-repl-buffer-name-shared`](https://www.racket-mode.com/#racket_002drepl_002dbuffer_002dname_002dshared), which it sounds like you're using. With the change to support multiple back ends, this function had to change to append the name of the back end. The default back end is `/` (all files on the local host). Ergo the "*Racket REPL </>*".

But even before that change, it was already the case that the REPL buffer name could be anything, really, due to `racket-repl-buffer-name-function`. So the most general/reliable way to find _some_ such buffer is probably to look through `buffer-list` for one whose `major-mode` is `'racket-repl-mode`. Maybe there's a better way but my first thought would be:

```elisp
;; Find some buffer whose major mode is racket-repl-mode
(cl-some (lambda (buf)
           (with-current-buffer buf
             (and (eq major-mode 'racket-repl-mode) buf)))
         (buffer-list))
```

**Comment by bhrgunatha** [comment]
Thanks, that makes sense. 

And yes, it's just for my own config. In the [documentation for `racket-repl`](https://github.com/greghendershott/racket-mode/blob/master/racket-repl.el#L217) you say it *can* be called directly... 

> But in some sense you'd be "using it wrong" ... 

Ha ha - then honestly, I never want to be right.   

The experience of using `racket-repl` with all the emacs machinery - and our own personal tweaks and configurations - behind it is **so far** superior to using `racket` in a shell (or using DrRacket or  xrepl) that I'm willing to put up with your disapproval :)

**Comment by greghendershott** [comment]
Ah, I see. :smile:

Probably "using it wrong", even in scare quotes, is (ahem) me writing it wrong.

I added that only after some people reported it didn't behave in certain ways. I wanted to set expectations. But if it's OK for you wonderful and no worries!
