### ISSUE TITLE
`racket-run-module-at-point` does not seem to function without a reader extension

### ISSUE THREAD

**Issue by zyrolasting** [greghendershott/racket-mode#622]
For each of these programs, position your cursor within the `test` submodule and run `racket-run-module-at-point`. Only the former behaves as expected.

`#lang racket/base (module+ test (write 'Hi))`
`(module anon racket/base (module+ test (write 'Hi)))`

I'm writing a self-hosting model that starts strictly without use of reader extensions, such that one file contains a growing module tree. The program requires that it's own source code contain exactly one `racket/base` module form. Not having `racket-run-module-at-point` in a program of that structure seems to leave me only with `(require (submod ...))` in the REPL. Is there a workaround?

Thanks for reading!

**Comment by greghendershott** [comment]
Thanks for reporting. That's a bug. Commit pushed. Will merge to main branch after I get all-green on the CI.

Note that the fix only works for `.rkt` files that contain a single, outermost `module` form -- but I think that's OK because that's the only scenario that the default Racket load handler supports.

**Comment by zyrolasting** [comment]
Appreciate the fast fix!
