### ISSUE TITLE
Encode search item correctly

### ISSUE THREAD

**Issue by sorawee** [greghendershott/racket-mode#623]
Write the program:

```
#lang racket
(require racket/draw)
bitmap%
```

and attempt to search for a documentation of `bitmap%`.

This fires up a browser to https://docs.racket-lang.org/search/index.html?q=bitmap%. However, this URL is not in a format that Scribble likes, and the entire page breaks down. The correct URL should be https://docs.racket-lang.org/search/index.html?q=bitmap%25.

See also: https://github.com/racket/scribble/pull/329

**Comment by greghendershott** [comment]
Thanks for reporting.

To clarify, this seems to be only for `racket-documentation-search`, a.k.a. <kbd>C-u C-u C-d C-d</kbd>, and when the `racket-documentation-search-location` variable is a format string such as the default `"https://docs.racket-lang.org/search/index.html?q=%s"`. That's the situation where the user search text needs to be encoded. I'll merge a fix for that.

[Whereas for other flavors, e.g. <kbd>C-c C-d</kbd>, with or without a single "prompt me" <kbd>C-u</kbd> prefix, this is N/A because the complete URL is coming from the Racket documentation database and is encoded appropriately. At least that is my experience. If anyone sees otherwise of course please chime in.]
