### ISSUE TITLE
Reloading modified code from file-less buffer

### ISSUE THREAD

**Issue by jasonhemann** [greghendershott/racket-mode#630]
I believe there's an edge case with the [conditional in the preceding fix](https://github.com/greghendershott/racket-mode/blob/7bcedccbd96578cb581199d89ea05406c2c2fc87/racket-repl.el#L492-L496), where modifications to code in the formerly file-less buffer aren't passed on to the racket repl.

Take the slightly-modified MWE

```
# -*- org-src-lang-modes: (("racket" . racket)); -*-
#+BEGIN_SRC racket
  #lang racket/base
  (define g "hello")
  g
#+END_SRC
```

If, for instance, I call `org-edit-src-code` with my mark in the racket code block, and then call `racket-run` this generates the expected temporary file and works as intended. If, however, I then modify the org-src buffer, say deleting the `(define g "hello")` on line 2, and then call `racket-run` again, this file still works. 

If you try the two variants in the opposite order (wits first the version with `g` undefined, and then add the definition) you see the opposite problem: the REPL buffer doesn't pick up the change. 

My thought was: is there a way to distinguish between buffers associated with these temp files, and buffers associated with real files, and always `write-region` if it's one of these temp files ? Would that be the right thing to do?

**Comment by greghendershott** [comment]
In the previous commit, I used `write-region` because the obvious normal thing to use -- `save-buffer` -- did not work. I should have thought more carefully _why_ it didn't work.

It looks like `org-edit-src-code` uses some "magic" where it installs a `write-contents-functions` hook that causes `save-buffer` not to write to the disk.

(You might think that `save-buffer` would be a pretty thin wrapper around `write-region`. I did... until diving into its source, for this issue. There's a lot going on. Including some hooks like this to customize what it means to "save a buffer". Which is cool, but making life a bit complicated at the moment.)

In a quick experiment, if I prepend my own value to `write-contents-function`, so that it is called first, and have it do the `write-region`, then both the initial and subsequent saves (really, to the file!) happen before each run.

At the moment I have:

```diff
modified   racket-repl.el
@@ -491,9 +491,20 @@ Otherwise if `racket--repl-live-p', send the command."
     (user-error "Racket Mode run command only works from a `racket-mode' buffer"))
   ;; When buffer-file-name is nil, as in #626, use a temp file.
   (unless buffer-file-name
-    (setq buffer-file-name (make-temp-file "racket-org-edit-" nil ".rkt"))
-    (write-region nil nil buffer-file-name)
-    (set-buffer-modified-p nil)
+    (let ((orig-buffer-name (buffer-name)))
+      (set-visited-file-name (make-temp-file "racket-org-edit-" nil ".rkt"))
+      (rename-buffer orig-buffer-name))
+    ;; org-src-mode adds to write-contents-functions a hook that
+    ;; interferes with `save-buffer' actually writing to file. Work
+    ;; around that by prepending our own hook, which saves and returns
+    ;; nil so that the org-mode hook will still later be called.
+    (when (and (boundp 'org-src-mode) org-src-mode)
+      (add-hook 'write-contents-functions
+                (lambda ()
+                  (message "howdy")
+                  (write-region nil nil buffer-file-name)
+                  nil)
+                nil t))
     (setq what (list (racket--buffer-file-name))))
   (unless (progn (racket--save-if-changed)
                  (racket--what-to-run-p what))
```

But I'm not quite ready to commit that, yet. Worried there are more edge cases and moving parts. Want to sleep on it, at least.

**Comment by greghendershott** [comment]
I merged a commit. This works in the scenarios I tried for org-src -- and avoids doing anything special otherwise.

As usual if you're still seeing problems please don't hesitate to reopen this issue or create a new one, whichever seems best to you.

**Comment by jasonhemann** [comment]
Aye aye, thank you very much!

**Comment by greghendershott** [comment]
Although a little frustrating at first ("why the heck isn't `save-buffer` saving to file???") this turned out to be a pretty interesting bug. I got some hands-on using `org-edit-src-code` which I barely knew existed. I learned that it sets up <kbd>C-x s</kbd> to save back to the parent org file instead of to disk. And I learned _how_ it does this, i.e. how `save-buffer` is more complicated than I realized, on top of which it can be customized by something to do who-knows-what. So thank you for such an educational bug to figure out and fix. :smile:
