### ISSUE TITLE
hash-lang,repl: error display handler doesn't write to port

### ISSUE THREAD

**Issue by Bogdanp** [greghendershott/racket-mode#672]
<details>
<pre>
((alist-get 'racket-mode package-alist))
((emacs-version "29.1")
 (system-type darwin)
 (x-gtk-use-system-tooltips UNDEFINED)
 (major-mode help-mode)
 (racket--el-source-dir "/Users/bogdan/.emacs.d/vendor/racket-mode/")
 (racket--rkt-source-dir "/Users/bogdan/.emacs.d/vendor/racket-mode/racket/")
 (racket-program "racket")
 (racket-command-timeout 10)
 (racket-path-from-emacs-to-racket-function UNDEFINED)
 (racket-path-from-racket-to-emacs-function UNDEFINED)
 (racket-browse-url-function racket-browse-url-using-temporary-file)
 (racket-documentation-search-location "https://docs.racket-lang.org/search/index.html?q=%s")
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-mode-lighter
  (:eval
   (racket--xp-mode-lighter)))
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function racket-repl-buffer-name-project)
 (racket-submodules-to-run
  ((test)
   (main)))
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-repl-history-directory "~/.emacs.d/racket-mode/")
 (racket-history-filter-regexp "\\`\\s *\\'")
 (racket-images-inline t)
 (racket-imagemagick-props nil)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "open")
 (racket-pretty-print t)
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (racket-mode-debugger . info)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-echo-area)))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (buffer-read-only)
 (column-number-mode)
 (dumb-jump-mode)
 (electric-indent-mode)
 (evil-local-mode)
 (evil-mode)
 (evil-surround-mode)
 (file-name-shadow-mode)
 (flx-ido-mode)
 (font-lock-mode)
 (global-auto-revert-mode)
 (global-eldoc-mode)
 (global-evil-surround-mode)
 (global-font-lock-mode)
 (global-hl-line-mode)
 (ido-everywhere)
 (ido-ubiquitous-mode)
 (ido-vertical-mode)
 (isearch-fold-quotes-mode)
 (line-number-mode)
 (mac-mouse-wheel-mode)
 (menu-bar-mode)
 (override-global-mode)
 (projectile-mode)
 (recentf-mode)
 (save-place-mode)
 (savehist-mode)
 (semantic-minor-modes-format)
 (server-mode)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (transient-mark-mode)
 (windmove-mode))
(disabled-minor-modes
 (abbrev-mode)
 (auto-fill-function)
 (auto-image-file-mode)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (blink-cursor-mode)
 (buffer-face-mode)
 (button-mode)
 (cl-old-struct-compat-mode)
 (comint-fontify-input-mode)
 (company-mode)
 (company-search-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (context-menu-mode)
 (cursor-face-highlight-mode)
 (dash-fontify-mode)
 (defining-kbd-macro)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (dired-isearch-filenames-mode)
 (dired-omit-mode)
 (diredp-breadcrumbs-in-header-line-mode)
 (edit-indirect--overlay)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (eshell-arg-mode)
 (eshell-command-mode)
 (eshell-proc-mode)
 (flycheck-mode)
 (flyspell-mode)
 (global-company-mode)
 (global-dash-fontify-mode)
 (global-dired-hide-details-mode)
 (global-flycheck-mode)
 (global-prettify-symbols-mode)
 (global-reveal-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-visual-line-mode)
 (hl-line-mode)
 (horizontal-scroll-bar-mode)
 (hs-minor-mode)
 (ibuffer-auto-mode)
 (ido-cr+-debug-mode)
 (image-minor-mode)
 (indent-tabs-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (lock-file-mode)
 (lost-selection-mode)
 (mac-auto-ascii-mode)
 (mac-auto-operator-composition-mode)
 (mac-font-panel-mode)
 (minibuffer-electric-default-mode)
 (mouse-wheel-mode)
 (next-error-follow-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (paredit-mode)
 (prettify-symbols-mode)
 (pyvenv-mode)
 (pyvenv-tracking-mode)
 (racket-hash-lang-repl-mode)
 (racket-smart-open-bracket-mode)
 (racket-xp-mode)
 (rainbow-delimiters-mode)
 (read-extended-command-mode)
 (rectangle-mark-mode)
 (reveal-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (sh-electric-here-document-mode)
 (shell-highlight-undef-mode)
 (size-indication-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (treesit-explore-mode)
 (treesit-inspect-mode)
 (undelete-frame-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (vc-dir-git-mode)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode)
 (xref-etags-mode))
</pre>
</details>

[This code](https://github.com/Bogdanp/Franz/blob/91283aa1aeef44c72d0d953d85bfb038998df159/FranzCross/main.rkt#L30-L38) reports that `message` is an empty string when triggered under the new REPL. Probably, racket-mode needs to write the output to the current error port in addition to the racket-mode buffer.

**Comment by greghendershott** [comment]
Thanks for the report.

The [`error-display-handler` documentation](https://docs.racket-lang.org/reference/exns.html#%28def._%28%28quote._~23~25kernel%29._error-display-handler%29%29) does say something that I neglected:

> An error display handler can print errors in different ways, but it should always print to the current error port.

Oops.

I can output the `exn-message` string to `current-output-port`, only. That's simple.

I'm not sure what to do about the extra information -- srclocs and context, if any. I really want that to be structured data, now. ^1

If I send that to the error port, as well as in the form of structured data, both, it will show up twice in the Racket Mode REPL.

If I don't send that to the error port, then code like you reported won't see it -- but presumably it wants that, if it's using error-display-handler instead of just exn-message.

So... dang. I'll need to mull this.

---

^1: The old Racket Mode error-display-handler had to go to some lengths to fully qualify pathnames and so on -- the visible user presentation had to include all the details. Whereas now I can send the original full details, and if things like `source-location->string` have elided some of that for user presentation (e.g. "<pkgs>/path/to/file.rkt") that's fine, I still have the real/full information.

**Comment by greghendershott** [comment]
I think probably it would suffice for the error-display-handler to check whether current-error-port is the special custom port that actually put items in a "repl-output-channel" for eventual retrieval by the front end.

If so, it can send the message and structured data that way.

Otherwise, if current-error-port is any other value (e.g. if it has been parameterized as in your reported code example), it should output to that port -- maybe even just using the original, default error-display-handler.

**Comment by greghendershott** [comment]
I thought about this more, convinced myself it makes sense, and pushed a commit like that.

Although your example seemed a little big for me to try quickly -- so please let me know if not good! -- I did what I believed to be some equivalent simpler smoke tests.

**Comment by Bogdanp** [comment]
Works great! Thanks!
