### ISSUE TITLE
FYI: Scribble HTML change

### ISSUE THREAD

**Issue by sorawee** [greghendershott/racket-mode#695]
I further refined the button group in https://github.com/racket/scribble/pull/392. So I create this issue as a FYI in case Racket Mode is needed to be adjusted similar to https://github.com/greghendershott/racket-mode/commit/a745a92579ff65d2941a1226383a80a00b0c490c.

Backward compatibility-wise, I would not care about the format that was introduced https://github.com/racket/scribble/pull/377 and is now superseded by https://github.com/racket/scribble/pull/392, since the change doesn't make it to a release for "general use".

**Comment by greghendershott** [comment]
Thanks for the heads up.

- Racket Mode might be OK because I opted just to ignore such elements. I think it will ignore them if they just moved. (But I'll double-check.)

- I'll change Frog which had a [test that needed to change](https://github.com/greghendershott/frog/commit/421bc2a2a9e193938a42553243dcc2d2dcb5520b).

**Comment by greghendershott** [comment]
Yep: Racket Mode seems OK. Merged change for Frog.  Thanks again for the heads up!
