### ISSUE TITLE
smart-open-bracket: 'Wrong type argument' error

### ISSUE THREAD

**Issue by 3rdLaw** [greghendershott/racket-mode#81]
Thanks again for racket-mode!

I was going to add a couple small improvements to the smart-open-bracket logic, so I fetched your master, but when I tried to type with it enabled *[* I kept getting the error **Wrong type argument: listp, 65**.

**Comment by greghendershott** [comment]
Dang that's embarrassing. I misplaced a doc string. I just pushed commit 01a69a2.

**Comment by greghendershott** [comment]
Just so you know, I _had_ tested this change interactively. :) But probably I had inadvertently tested some remnant of a previous definition lurking in the Elisp environment. That it is so dynamic can be wonderful... but it can also trip me up. That's why I really like the DrRacket and racket-mode idea that Run means, "start fresh with the contents of the source file".

I think part of the answer is I ought to to add more ERT unit tests.

Anyway the commit I pushed fixes this for me, so I'm going to close this. I'm sorry for the confusion, and thanks in advance for the enhancements you're planning to contribute!
