### ISSUE TITLE
Need to `(require redex)` twice in REPL

### ISSUE THREAD

**Issue by philnguyen** [greghendershott/racket-mode#93]
I'm just guessing it has something to do with the "one time instantiation of racket/gui/base". Here is how to reproduce it:

 Load an empty file:

``` Racket
#lang racket/base
```

In the REPL, type:

``` Racket
(require redex)
 ; on-demand one-time instantiation of racket/gui/base
```

Doing this the first time will fail:

``` Racket
traces
; traces: undefined;
;  cannot reference an identifier before its definition
```

Loading `redex` again solves the problem

``` Racket
(require redex)
traces
```

**Comment by greghendershott** [comment]
I'm not surprised. Racket-mode installs a `current-module-name-resolver`
that checks for `racket/gui/base` being loaded. The first time, it does
the one-time instantiation -- and effectively re-`racket-run`s the
buffer/file. (Because normally how this would be caught is while
evaluating the buffer/file, and we need to "start over", creating a GUI
eventspace, and other gory details.)

Of course, a key racket-mode feature is that `racket-run` gives you a
"clean slate" -- discarding everything done/created in the REPL.
Including, in this case, the `(require redex)`. Whereas in the
more-typical case thatf the `(require redex)` were in the file, it would
work as you would expect.

---

Theoretically I could, in this special case of the gui instantation, try
to "replay the REPL" -- re-evaluate all the expressions in it, since the
previous user-initiated `racket-run`.

However I think that would be a lot of work -- and especially likely to
be other-bug-creating work -- for what feels to me like a corner case.
And one where the user work-around is <kbd>M-p RET</kbd>. :)

So I think for now I'm going to suggest that the resolution be to "fix"
this by documenting it, not in code?

**Comment by greghendershott** [comment]
I'm not surprised. Racket-mode installs a `current-module-name-resolver`
that checks for `racket/gui/base` being loaded. The first time, it does
the one-time instantiation -- and effectively re-`racket-run`s the
buffer/file. (Because normally how this would be caught is while
evaluating the buffer/file, and we need to "start over", creating a GUI
eventspace, and other gory details.)

Of course, a key racket-mode feature is that `racket-run` gives you a
"clean slate" -- discarding everything done/created in the REPL.
Including, in this case, the `(require redex)`. Whereas in the
more-typical case thatf the `(require redex)` were in the file, it would
work as you would expect.

Theoretically I could, in this special case of the gui instantation, try
to "replay the REPL" -- re-evaluate all the expressions in it, since the
previous user-initiated `racket-run`. 

However I think that would be a lot of work -- and especially likely to
be other-bug-creating work -- for what feels to me like a corner case.
And one where the user work-around is <kbd>M-p RET</kbd>. :)

So I think for now I'm going to suggest that the resolution be to "fix"
this by documenting it, not in code?

**Comment by philnguyen** [comment]
I see. I agree it's reasonable just to document it.
